### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by davidthornton**
Following from https://github.com/react-boilerplate/react-boilerplate/pull/753, which was closed due to inactivity, I have reopened this PR and applied some changes that take advantage of the stability and feature updates that Docker has provided in the intervening period.

The main changes over and above the previous PR are:

1. A focus on using Docker in development rather than production (these days k8s, static hosting or similar is probably a better strategy for orchestrating a react container in production)
2. An update to use node 10 (`node:10-slim` is the base Docker image from which this container derives)
3. The addition of a `docker-compose.yml` file which streamlines package dependency and startup installation time. From fAustralia, a `docker-compose build` took ~3 minutes to pull all dependencies and get up and running. The base OS accounts for 67 Mb and a fully installed development environment is about 740 Mb in size.
4. A focus on optimal DX: when using Docker with mounted volumes, touch reloading works perfectly and only three commands are required to update `npm` dependencies from other contributors. Only a single command is required to locally update dependencies: `docker-compose exec yarn add {NEW_PACKAGE_NAME}`.

### CODE REVIEW

**Comment by mxstbr** [comment]
Deploy preview for *react-boilerplate* failed.

Built with commit e5a54a9b4c2e0d959997f1eb3c4d6ec36a8c61e8

https://app.netlify.com/sites/react-boilerplate/deploys/5b1e3c9c3672df396f76ccb2

**Comment by julienben** [comment]
Hey David, 

Thanks for the contribution!

I don't want to approve this without having some input from the other maintainers as I feel there's been quite a bit of discussion around adding Docker support and I'm not sure where the consensus landed. @gretzky Thoughts?

Unrelated to that, I have a couple questions:
1.  Does hot reloading work in this setup? Take a look at #2232.
2. The Netlify build preview is working but the setup process has a bunch of errors that I don't believe I've seen in other PRs. Could you look into that?

Cheers!

**Comment by davidthornton** [comment]
Hi @julienben,

I've been following the sentiment of this repository since early 2017, including by offering to contribute to #753 and understand that adding further build tools may crowd out the purpose of react-boilerplate.

As such, I'm prepared to take all comments and address them to the satisfaction of the entire team.

In respect of #2232 specifically, I can confirm that on my MacBook Pro with the latest version of Docker for Mac installed I can pull down this PR, run:

    docker-compose up localdev

and have the image built and running at `http://localhost:3000` in about 8 minutes. Subsequent express server starts are about 30 seconds each.

Crucially, due to the way in which I have structured the `Dockerfile` and the way it interacts with `docker-compose.yml`, hot reload times are about 5 seconds each - i.e. just the time that webpack takes rebuild the bundle. I can confirm that the code is hot pushed to the browser which reloads automatically as well.

I expect this to work upon any platform that Docker is available, and this is due to the way that Docker handles volume mounts. However #2232 does appear to create a similar directory mount structure, and I can't see the exact reason why modifying any webpack related code would be necessary in order to get touch (hot) reload working.

There are a few reasons, however, why it may not work for others; and this might be due to the filesystem notify events not properly being propagated by the Docker engine. Indeed, Docker for Mac suffered from this problem for a time two years ago.

This PR could be tested in a Windows and Linux development environment for further assurance, however I believe this `Dockerfile`/`docker-compose.yml` setup is optimal for node servers on the basis of certain articles elsewhere on the internet (for example https://medium.com/lucjuggery/docker-in-development-with-nodemon-d500366e74df and https://blog.codeship.com/using-docker-compose-for-nodejs-development/) and due to the fact that I've been running this in "developer production" i.e. my primary method of local development, for a year now.

With respect to the netlify build errors, is it possible you're referring to https://app.netlify.com/sites/react-boilerplate/deploys/5b1e3c9c3672df396f76ccb2 which was a build that failed because I had not created the PR correctly, triggered by e5a54a9. I needed to resolve merge conflicts from `dev` which I did in 59d0e44. From what I can see, the subsequent netlify build succeeded without any errors (but the same warnings as in https://app.netlify.com/sites/react-boilerplate/deploys/5b1acc6db312740d68c4087e).

If there is anything else I need to do or address, just let me know and I'll be happy to respond!

**Comment by julienben** [comment]
Thanks for the super detailed response! I have nothing against including docker support. It's widely-adopted enough as a build tool to justify its presence in the boilerplate IMO. Will wait to see what @gretzky thinks about it.

In any case, it might necessary to set this up as a follow-up to #2235 (which will probably overwrite any changes we merge in the meantime).

**Comment by davidthornton** [comment]
Yes I figured #2235 might change a few things. I'm happy to wait for the dust to settle after merging that and then rebase this on top of it. I don't imagine much will need to change, but there could be a few things that need addressing which I'd be happy to do.

**Comment by gretzky** [comment]
Once we get v3.6.0 out this is worth a revist I think. I definitely think there are a few other PRs on adding in integrations similar or on the same idea as Docker-- and it's definitely up for debate how much integration we want. 

ttl;dr i feel like we might go down a long road if we decide to add docker, and we have to look at the roadmap of rbp before we do so

**Comment by davidthornton** [comment]
I have just cherry-picked this commit on top of v3.6.0 and as a preliminary matter it appears to work under node 10.

I expect this to work under the 3.6.0 dev branch, but will await that branch to rebase/recreate this PR.

**Comment by davidthornton** [comment]
Closing this in favor of #2282

**Pull request closed without merging**
