### PR TITLE
React Boilerplate v4.1

### PR DESCRIPTION
**Pull request by julienben**
# v4.1: "The One with Hooks, Redux (Redux Hooks)" Edition

It's been a little over 2 months since we released v4.0. We haven't had any huge changes since but IMO it would be nice to do a maintenance release.

Anybody have any thoughts or additions? Anything we should be including urgently?

I haven't written a full changelog yet but here are the highlights:
- Switch to react-redux's hooks API
- Very nice testing improvements (Thanks to @tigranpetrossian)
	- Easier test navigation with jest-watch-typeahead
  	- More declarative component tests using jest-dom/extend-expect
- Tests for loadable.js
- Many dependency updates
- New polyfill setup (after deprecation of @babel/polyfill)
- BONUS: Thanks to a bugfix in babel-plugin-styled-components, we now support the css prop

### CODE REVIEW

**Comment by justyn-clark** [comment]
👍

**Comment by Hudison** [comment]
Is there any previson of the release date? Thanks!

**Comment by lipaksahu** [comment]
Can I start using from the `dev` branch ?

**Comment by julienben** [comment]
@Hudison We're waiting for the final release of styled-components v5 so that this release of RBP won't be obsolete a few days after it comes out.

@lipaksahu Yes, you can always do that.

**Comment by incepter** [comment]
Hello, I saw this PR and used it.
Can you please tell us what is still in progress ? I want to bootstrap a project and i'm thinking of using this version rather than the released one. If it will be released in the next few days i think i can wait, else please tell us when it will be released.

PS: It was an incredible sophisticated work.

**Comment by julienben** [comment]
@incepter You can use the `dev` branch without any issues. Everything should be ready and working. (We're just waiting for the final release of styled-components v5 before our own release.)

**Comment by incepter** [comment]
> @incepter You can use the `dev` branch without any issues. Everything should be ready and working. (We're just waiting for the final release of styled-components v5 before our own release.)

Ok thank you a lot @julienben

**Comment by thiagoandf** [comment]
Any plans to upgrade to react-intl v3+ soon?

**Comment by julienben** [comment]
We'll upgrade before releasing 4.1. If you'd like to help with this particular upgrade, you're welcome to open a PR. [This](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md) is the upgrade guide from react-intl.

**Comment by julienben** [comment]
@jwinn Did you set up Codacy? Can we remove it? It's always reporting that the PRs are "Not up to standards" but I'm fairly sure most of the "issues" it reports are wrong. Like this:

image

(And then the PR appears to not have passed checks even though it passed linting and testing on both Travis and Appveyor.)

**Comment by jwinn** [comment]
@julienben I can either disable/modify PMD (source code analyzer) and the RemarkLint (markdown linter), or remove Codacy completely. If it's lending no value--beyond what the project gets with eslint etc., then I see no real reason to keep it in place, as it just adds another item in the project that needs maintained. Thoughts?

**Comment by julienben** [comment]
This is kinda funny... I set up Codacy quite a while back (they're doing a strong marketing push clearly). Not long after, I removed it because I didn't feel like it offered any value in addition to our existing static analysis. But it never disappeared from our PR code checks so I assumed it was a glitch in the setup. The truth is you probably set it up around the same time I removed it. 😅

Up to you what we do with it but if it stays, can we just make sure it:

1. doesn't give false errors (like above where the "unnecessary block" error comes from a parser which doesn't understand that `{...utils, link}` is an object and not a block) and
2. provides legitimately useful feedback that we can't also receive through other tools?

**Comment by jwinn** [comment]
Understood. I<s>'ll just remove</s> removed it as I don't feel this offers any added value to the BP's maintenance/development process.

**Comment by julienben** [comment]
Great, thanks! (Btw, if it had any static analysis tools - other than ESLint - that might offer valuable insights, we can consider adding it locally instead of via an external tool so that users of RBP can benefit from it too.)

**Comment by julienben** [comment]
The original plan was to release this with `styled-components` v5 but it's been stuck on beta 8 since July 1st so the new plan is to release this at the same time as [the injectors project](https://github.com/react-boilerplate/react-boilerplate/issues/2698).

There are two pending items IMO:
- Upgrading `react-intl` to v3. Not a trivial task. @mhatvan gave it a shot [here](https://github.com/react-boilerplate/react-boilerplate/pull/2721) but it's incomplete/broken and requires some assistance from a benevolent volunteer (pleonasm?).
- Also, `react-helmet` uses the deprecated `componentWillMount` and has long been abandoned anyway so it's time to consider alternatives and migrate away from it.

**Comment by danielnass** [comment]
@julienben could we change `react-helmet` for `react-helmet-async`?

https://open.nytimes.com/the-future-of-meta-tag-management-for-modern-react-development-ec26a7dc9183
https://github.com/staylor/react-helmet-async

**Comment by julienben** [comment]
@danielnass LGTM! Would you like to open a PR? Or would someone else like to take it?

**Comment by mcmxcdev** [comment]
@julienben I would work on a PR if that is fine with @danielnass.

**Comment by julienben** [comment]
Re-opening this as v5.0 instead. Too many changes.

**Pull request closed without merging**
