### PR TITLE
Generate passing tests for components/containers

### PR DESCRIPTION
**Pull request by mjhost**
## React Boilerplate

Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.

**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.

Before opening a pull request, please ensure:

- [x] You have followed our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md)
- [x] Double-check your branch is based on `dev` and targets `dev` 
- [ ] Pull request has tests (we are going for 100% coverage!)
- [ ] Code is well-commented, linted and follows project conventions
- [ ] Documentation is updated (if necessary)
- [x] Internal code generators and templates are updated (if necessary)
- [x] Description explains the issue/use-case resolved and auto-closes related issues

Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)

**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [MIT License](https://github.com/react-boilerplate/react-boilerplate/blob/master/LICENSE.md).

as proposed in  #2415 here is my suggestion to generate a basic passing test that asserts that console.error has not been called in a shallow rendering.

### CODE REVIEW

**Comment by mjhost** [comment]
It's just something that i had that helped me during the development. 

1. I don't really know what there should be against generation of a small passing test. You won't stop anyone from writing deeper tests, and it will need to be expanded to test all branches.
2. this one is just testing that there are no console errors, aka it catches `"Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports."` for example

**Comment by mjhost** [comment]
by the way @gretzky wanted to see the implementation :)

**Comment by julienben** [comment]
1. You lose the very explicit notice of the failing test which says "Expect to have unit tests specified". If you have a passing test by default, devs are less likely to write additional tests IMO.

2. I personally like that it fails on React warnings but I'm not sure how popular that would be. @gretzky You have an opinion on this? Or this PR as a whole?

@mjhost I think your test makes sense as an addition to the current test, not a replacement. We should have both yours and another called "Expect to have **additional** unit tests specified" which compares `false` to `true` as it does now. Perhaps it could even have a comment with the link to the test documentation in this repo. And then devs are really encouraged to write more tests and learn about it. What do you think?

(BTW, please take a look at your diff. All the indentation in `stateless.js.hbs` was removed.)

**Comment by mjhost** [comment]
sorry about the indentation, prettier just walked in and i didn't realize. 
about the proposal of making it an addition to the existing test, it makes sense. I'll commit accordingly.

**Comment by julienben** [comment]
Yeah `prettier` likes to invite itself where it's not welcome. I wasn't able to fix it with `.prettierignore` if I remember correctly. Instead, you can add: 

```json
"[handlebars]": {
  "editor.formatOnSave": false,
}
```

to your VS Code config (if that's your IDE of choice).

**Comment by julienben** [comment]
Thanks @mjhost

**Pull request merged**
