### PR TITLE
Prepare for v3.5 release

### LINKED ISSUE #1776: Prepare for v3.5 release
i [created a milestone](https://github.com/react-boilerplate/react-boilerplate/milestone/4) to aggregate outstanding PRs we want to include in next release... i think we're a little overdue :) please let me know what you guys think

cc @react-boilerplate/core

edit: raw link - https://github.com/react-boilerplate/react-boilerplate/milestone/4

### PR DESCRIPTION
**Pull request by justingreenberg**
Closes #1776 

@react-boilerplate/core started drafting release notes https://github.com/react-boilerplate/react-boilerplate/releases will try to wrap up later tonight... please feel free to chime in :)

### CODE REVIEW

**Comment by Dattaya** [comment]
@justingreenberg, @KarandikarMihir, please take a look at #1931

**Comment by KarandikarMihir** [comment]
@Dattaya Sorry I didn't get a chance to! I'm going to test dev branch today for the last time.

**Comment by blling** [comment]
Any news?

**Comment by openjambe** [comment]
What is the status of the v3.5 ?
How can I contribute for the next release ?

**Comment by justingreenberg** [comment]
@blling i have been traveling i'm sorry for delayed release
@openjambe thank you for offering to help :)

features are locked, we just need to wrap up the release itself... since it contains major breaking changes, we need a thorough changelog (could probably use a blog post, but i'll ship before)

this release is very much on the radar :) thanks for the continued patience everyone

**Comment by justingreenberg** [comment]
fuck it i have a free hour i'm gonna do this now... manually creating changelog

**Comment by openjambe** [comment]
Fantastic 🥇 Thank you

**Comment by danphamus304** [comment]
Pull request

**Comment by danphamus304** [comment]
https://github.com/react-boilerplate/react-boilerplate/commit/4c053c37d025ae715b49f5fee4789f62e1d20634

**Comment by danphamus304** [comment]
https://github.com/react-boilerplate/react-boilerplate/commit/c28e1539cefb3957fb4cfd848bf1efd34a0725d8

**Pull request merged**
