### PR TITLE
Update package.json version to 3.7.0

### PR DESCRIPTION
**Pull request by julienben**
Self-explanatory ;)

### CODE REVIEW

**Comment by gretzky** [comment]
HAHA i beat you to it 😂 😂

**Comment by gretzky** [comment]
Let's race and see who's CIs pass first

**Comment by gretzky** [comment]
Nvm, mine was hosed

**Comment by julienben** [comment]
I can cancel your AppVeyor builds anyway 😈

**Comment by gretzky** [comment]
Do you want to draft a release? Or I will?

**Comment by julienben** [comment]
Already started it. Will finish it tomorrow morning. (It's evening here.)

**Comment by julienben** [comment]
Forgot to update version in package-lock.json as well... Do you mind adding it to this PR before merging?

**Comment by julienben** [comment]
(I don't have a computer with a dev setup with me)

**Comment by gretzky** [comment]
All set

**Comment by julienben** [comment]
Thanks!!

**Comment by gretzky** [comment]
of course you already started it, Mr Over Achiever!!!! jk, great work, i'll spread the good word on twitter

**Pull request merged**
