### PR TITLE
add SSR example to docs

### PR DESCRIPTION
**Pull request by gretzky**
super quick/easy change. i added an SSR example to the table of contents so its right there if anyone goes looking for it.

### CODE REVIEW

**Comment by jwinn** [comment]
Should the PR be merged to dev, then to master, or is dev in an unknown state? (Trying to get back up-to-speed as I've been away a while)

**Comment by gretzky** [comment]
Dev is, I think (correct me if wrong @julienben) in a good state. I figured a minor doc change to master regarding SSR wouldn't hurt since we get asked about it pretty often 😅

**Comment by jwinn** [comment]
I don't disagree with it going into master. I was under the impression that we wanted `dev` to be in-sync and ahead of `master`. So the process was: changes are made to `dev`, then propagated to `master`, with any semantic version and changelog updates, where required, made as well--in this case being unnecessary.

My initial impetus for the query, though, was I wasn't sure on the state of `dev`--believing it in a good state, but I wasn't completely sure and wanted to verify. Are we still using gitter to have these kinds of discussions, or is there somewhere else we can chat? :smile:

**Comment by julienben** [comment]
@jwinn We do have a clean dev branch now.

@gretzky I think a link in the TOC is a bit confusing. People click there expecting to remain on the same page, not be taken to a different repo. Could the TOC item link instead to a short paragraph in README.md which briefly explains your SSR project and links to the repo from there?

About merging this directly to master: Fine by me so long as we rebase dev on top of master right away to keep the history clean. Alternatively, we could merge this into dev and do a small 3.6.1 release.

**Comment by julienben** [comment]
It might also be the perfect opportunity to add a link to @mjangir's electron version of RBP (#2288)

**Comment by julienben** [comment]
Closing in favor of #2372.

**Pull request closed without merging**
