### PR TITLE
feat(core): Set Referrer Policy to "origin" using document meta tag

### PR DESCRIPTION
**Pull request by JonathanStoye**
Add `<meta name=“referrer” content=“origin”>` to make the application more secure by not sending the full url to servers other than the origin.

### CODE REVIEW

**Comment by KarandikarMihir** [comment]
Nice addition. For anyone who wants more info on this, I found a [wiki](https://wiki.whatwg.org/wiki/Meta_referrer).

**Comment by JonathanStoye** [comment]
Weird is, that this tag seems to be still a draft even though all browsers support it. 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta

**Comment by justingreenberg** [comment]
reference - https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-delivery-meta

**Comment by oscar-broman** [comment]
The quote marks are wrong. This will set the values to `“referrer”` and `“origin”`.

**Comment by justingreenberg** [comment]
@oscar-broman good catch... this is using left/right quotations

```
  "   U+0022 QUOTATION MARK  ** this is what we need to be using **
  “   U+201C LEFT DOUBLE QUOTATION MARK
  ”   U+201D RIGHT DOUBLE QUOTATION MARK
```

@JonathanStoye would you mind opening a new PR to fix this?

**Comment by JonathanStoye** [comment]
@justingreenberg I will!

**Comment by JonathanStoye** [comment]
@justingreenberg @oscar-broman https://github.com/react-boilerplate/react-boilerplate/pull/1976

**Pull request merged**
