### PR TITLE
refactor(react-router): Import only necessary components

### PR DESCRIPTION
**Pull request by sorin-davidoi**
Instead of importing the entire library, cherry-pick the components we use.
This is [supported and encouraged](https://github.com/ReactTraining/react-router/blob/master/docs/guides/MinimizingBundleSize.md) by react-router.

Reduces the size of the main bundle by 9 kB (709 kB -> 700 kB) - we are no longer implicitly importing `history/createHashHistory` and `history/createMemoryHistory`.

### CODE REVIEW

**Comment by KarandikarMihir** [comment]
I thought tree-shaking feature of webpack 2 kicks in and the unwanted modules are stripped down.. 🤔

**Comment by gihrig** [comment]
@KarandikarMihir From my limited understanding:

`import { applyRouterMiddleware, Router, browserHistory } from 'react-router';`

Is effectively importing all of react-router and then, using ES6 destructuring to assign applyRouterMiddleware, Router and browserHistory to what are effectively local constants. 

(I know that does not agree with orthodox thought, but the the concept of 'Hoisting' is another example of orthodox thought making an unnecessary abstraction over the simplicity of a two-pass compile process where vars are processed first, then statements).

In any case, I believe tree shaking can only eliminate library code that is not (explicitly or implicitly) imported.

@sorin-davidoi Could you post some before and after charts using, for example [webpack-visualizer](https://chrisbateman.github.io/webpack-visualizer/) ?

See: #1309

**Comment by sorin-davidoi** [comment]
@KarandikarMihir From what I understand, tree-shaking only applies to ES6 modules, while most libraries ship as CommonJS modules (see "The Underlying problem" section from [here](https://medium.freecodecamp.com/tree-shaking-es6-modules-in-webpack-2-1add6672f31b#.cplzfgomg#22c4)).

Attaching screenshots obtained with [webpack-bundle-analyzer](https://github.com/th0r/webpack-bundle-analyzer) and webpack-visualizer.

Before:
screen shot 2017-02-23 at 10 10 13
screen shot 2017-02-23 at 10 12 22


After:
screen shot 2017-02-23 at 10 07 22
screen shot 2017-02-23 at 10 13 36

**Comment by samit4me** [comment]
LGTM :sparkles:

**Comment by KarandikarMihir** [comment]
@gihrig 
> 'Hoisting' is another example of orthodox thought making an unnecessary abstraction over the simplicity of a two-pass compile process.

I couldn't agree more. 

@sorin-davidoi Well, this was a good learning experience for me. Awesome! :sparkles:

**Comment by gihrig** [comment]
AppVeyor and Chrome are not seeing eye-to-eye...

>Download of googlechromestandaloneenterprise64.msi (48.26 MB) completed.
Error - hashes do not match. Actual value was '1450DE87F0289CE725DF1C138BBA2666304FB94BF4476B03C06D058C999D4805'.
ERROR: Checksum for 'C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\GoogleChrome\56.0.2924.87\googlechromestandaloneenterprise64.msi' did not meet 'c47ff551ff8b251268905cd87fb299959e6bcb3640a3e60085a3a7dbf176845f' for checksum type 'sha256'. Consider passing --ignore-checksums if necessary.
The install of googlechrome was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\GoogleChrome\tools\chocolateyInstall.ps1'

**Comment by samit4me** [comment]
I think there was a similar problem with #1611, which @tmf found a way around.

**Comment by KarandikarMihir** [comment]
Awesome, merging this! @sorin-davidoi Thanks for all your work :)

**Pull request merged**
