### PR TITLE
Feature: ErrorOverlayPlugin 

### PR DESCRIPTION
**Pull request by Can-Sahin**
Adding webpack plugin to display errors like `react-error-overlay` of `create-react-app`. Otherwise it just displays a white blank screen in case of errors.

Example screenshot

Screen Shot 2019-12-02 at 16 36 39

### CODE REVIEW

**Review by julienben — APPROVED** [review]
Looks great! This is a nice addition.

Just one thing: Adding yourself to .all-contributorsrc isn't enough for your profile to appear in the contributors table. I think you simply need to run `npx all-contributors generate` to update the table in README.MD. See [here](https://allcontributors.org/docs/en/cli/usage).

**Review by vineyardbovines — APPROVED** [review]
Definitely useful!

**Comment by Can-Sahin** [comment]
@julienben 

when i run the cli it removes all contributors from readme. `add` command throws error. No idea :S So i though when someone runs the command it will add me eventually ?

**Comment by julienben** [comment]
NP, I'll take care of it in my Redux Toolkit documentation branch.

**Comment by julienben** [comment]
@Can-Sahin The fix is [here](https://github.com/react-boilerplate/react-boilerplate/commit/3409860ed5e6933d9214a14ef496e5af3c358a6c). The issue was a trailing comma when you added yourself. It's JSON so invalid syntax ;)

**Pull request merged**
