### PR TITLE
fix(eslint): Enable rule react/no-array-index-key

### LINKED ISSUE #1503: New eslint-plugin-react rules complain "error Do not use Array index in keys"
Updated eslint-plugin-react rules disallow use of array index as key.

Error: ~/react-boilerplate/app/components/List/index.js 13:31
error Do not use Array index in keys react/no-array-index-key

Disable "react/no-array-index-key" in package.json
See: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md

To reproduce:
confirm #1501 has been merged
checkout current `dev` branch
remove  "react/no-array-index-key" from package.json
`npm test`

Boilerplate 3.4+ `dev` branch (ad871d7a1b70cec5b365fdc30eb86ee7e189158f)
Node 7.4.0
npm 4.1.1
yarn 0.19.1
Mac OS 10.11.6
Chrome 55.0.2883.95 (64-bit))

### PR DESCRIPTION
**Pull request by carloscuatin**
Fixes #1503

### CODE REVIEW

**Comment by carloscuatin** [comment]
@gihrig the component `ListItem` don'ts accept a `object` example:

```js
const items = [
  { id: 1, name: 'Hello' },
  { id: 2, name: 'World' },
];
```

Which would be the best option to pass another component that accepts the property established by the fake state ?

**Comment by gihrig** [comment]
@carloscuatin Off hand, I don't have an answer for that...

Anyone else?

**Comment by carloscuatin** [comment]
```js
const items = [
  { id: 1, name: 'Hello' },
  { id: 2, name: 'World' },
];
const Item = ({ name }) => <div>{name}</div>;
const renderedComponent = render(
  <List items={items} component={Item} />
);
```

possible solution @gihrig

**Comment by gihrig** [comment]
@carloscuatin That looks good, and it works ✨ 

A few issues though:
1. `const Item` Item is not an object or Component, it should be lowercase.
2. Eslint has an issue with 
```javascript
const item = ({ name }) => <div>{name}</div>;
```
image

Suggest adding ` // eslint-disable-line react/prop-types`

**Comment by KarandikarMihir** [comment]
@carloscuatin I tried the exact same thing, but it didn't work 😕 Maybe I missed something. Let's go with this if it works 👍

**Comment by gihrig** [comment]
@KarandikarMihir 

>  I tried the exact same thing, but it didn't work

What happened?

Current iteration works for me...

@carloscuatin Another win for code quality ✨  
Thanks for hanging in there through all the back and forth!

**Pull request merged**
