### PR TITLE
Subfolder deployment

### PR DESCRIPTION
**Pull request by nshimiye**
## React Boilerplate

Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.

**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.

Before opening a pull request, please ensure:

- [x] You have followed our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md)
- [x] Double-check your branch is based on `dev` and targets `dev` 
- [x] Pull request has tests (we are going for 100% coverage!)
- [ ] Code is well-commented, linted and follows project conventions
- [x] Documentation is updated (if necessary)
- [ ] Internal code generators and templates are updated (if necessary)
- [x] Description explains the issue/use-case resolved and auto-closes related issues

Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)

**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [MIT License](https://github.com/react-boilerplate/react-boilerplate/blob/master/LICENSE.md).

## Description
My Devops team has ran into issues while deploying the app because they were using an NGINX server that serves other apps.
So, I searched for solutions and came up with one of **[using environment variables to dynamically change the basename during build process.](https://medium.com/friday-knowledge/webpack-compiler-placeholders-3598f5f723b9)**

My thinking is that documenting the process is enough.
However, the changes that I made, do not affect current development setup. So, I chose to include them.

### CODE REVIEW

**Comment by gretzky** [comment]
Thanks for bringing this up! It looks great.

My recommendation would be to put all of your code changes into that section of the docs rather than make the changes in the code. For us, it's a lot harder to justify making code changes for just 1 use case-- we want it to be skeletal, if that makes sense.

**Comment by julienben** [comment]
Thanks for this! I think it's a great addition.

I agree with @gretzky though. Can we bring the code changes into the `deployment.md` instructions?

For a few reasons:
- This is just too rare of a use case to force a potentially brittle change onto all users. (I say brittle because all the changes make sense when you look at them from this PR but might be hard to understand without the context.)
- It only works for people deploying to NGINX or Apache, no? If yes, it needs to be specified. People wanting to do the same thing on, say, Netlify would have to do it differently.
- The code change would've also needed to be reflected in the template app's `history.js` file.

However, let's keep the switch to Webpack's EnvironmentPlugin. I wasn't aware of it but it's definitely nicer than the current version.

**Comment by nshimiye** [comment]
@julienben and @gretzky make sense! I will make the changes later today

**Comment by nshimiye** [comment]
@julienben and @gretzky I have made the changes! Let me know if that looks fine

**Comment by nshimiye** [comment]
@julienben fixed as requested!

**Comment by julienben** [comment]
Thanks for your diligence!! Will merge this as soon as I'm back in front of a computer.

**Pull request merged**
