### PR TITLE
Migrate from pre-commit to husky

### PR DESCRIPTION
**Pull request by avdeev**
Related with #2056 

Work correctly

```bash
Mac-mini-Alexey:react-boilerplate alexeyavdeev$ git commit -m "feat: migrate from pre-commit to husky"
husky > npm run -s precommit (node v8.9.0)

 ↓ Running tasks for *.js [skipped]
   → No staged files match *.js
```

### CODE REVIEW

**Comment by gretzky** [comment]
Hey @avdeev for some reason this build stalled out on node v7 -- I can check at some point but let me know if you get to it before me

**Comment by avdeev** [comment]
@gretzky It worked for me on Node.js v7.10.1.

Can you restart the build?

**Comment by mxstbr** [comment]
Deploy preview failed.

Built with commit 10a0555bbb766ee13749f3b5857fce808d314f86

https://app.netlify.com/sites/react-boilerplate/deploys/5a384df5a6188f6777f20dce

**Comment by blling** [comment]
I restart the job but still failed, error as follows:
```javacript
yarn install v1.3.2

warning You are using Node "7.10.1" which is not supported and may encounter bugs or unexpected behavior. 
Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"

error An unexpected error occurred: "Invalid number of spaces".
```

**Comment by avdeev** [comment]
@mxstbr @blling Some error with yarn.lock. Fixed.

@mxstbr @gretzky Can we remove support of Node.js 7? 8 is active LTS now.

**Comment by blling** [comment]
Need `rebase` `master` :)

**Comment by gretzky** [comment]
@avdeev I'll open up a PR on node 7. You're right, 8 should be good to go.

**Comment by avdeev** [comment]
@blling Do it #2077 :)

**Comment by blling** [comment]
@avdeev  Conflicts need to be resolved in this PR :)

**Comment by avdeev** [comment]
@blling Done 👍  !
Is all right?

**Comment by blling** [comment]
LGTM, thanks!

**Pull request merged**
