### PR TITLE
removed route names from app/routes

### PR DESCRIPTION
**Pull request by beardedtim**
This commit will close issue #1287 

I have ran tests and it looks like this does not affect anything.

### CODE REVIEW

**Comment by beardedtim** [comment]
@KarandikarMihir didn't even catch that! I suppose I should have dove deeper into the codebase before making the PR. I made that edits and pushed to the same branch. Let me know if I was silly and missed anything else!

**Comment by KarandikarMihir** [comment]
@beardedtim It's alright! 😄  `templates` is hidden away from the core parts and it's only natural that you didn't notice it. Here's my LGTM to your latest commit. 👍 :wink: 

I've read every comment from the [original issue](https://github.com/ReactTraining/react-router/issues/1840) just to make sure that this change is indeed harmless. If anybody thinks otherwise, now is the time.

**Comment by KarandikarMihir** [comment]
@beardedtim Hi. There's one more change that we should make. Please remove [this line](https://github.com/react-boilerplate/react-boilerplate/blob/master/internals/generators/route/route.hbs#L3) so that generator won't create `name` property.

**Comment by beardedtim** [comment]
@KarandikarMihir I removed it from there and from `routeWithReducer.hbs` because I figured if we are removing it from all routes that the reducer doesn't need it either.

**Comment by KarandikarMihir** [comment]
@beardedtim Good catch! Thanks very much 👍

**Comment by KarandikarMihir** [comment]
@beardedtim Good catch! Thanks very much 👍 

@gihrig Can you please take a look at this? It's ready.

**Pull request merged**
