### PR TITLE
Resized the banner to 768px width (1.2MB -> 70KB)

### PR DESCRIPTION
**Pull request by tomazy**
That's the maximum width we display it with in the header.

It also makes the app a bit lighter - I'm currently on 3G so I care :)

Processed using Gimp on macOS with 90% of the original quality.

### CODE REVIEW

**Comment by KarandikarMihir** [comment]
Hi @tomazy Please follow the guidelines listed under [contributing.md](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md). Create an issue for this PR, have a go from one of the members of RBP and then you can send a PR. This helps us streamline everything. 

Thanks for contributing! :sparkles:

**Comment by gihrig** [comment]
@tomazy @KarandikarMihir If I'm mistaken please forgive the implication, but I think @tomazy may have been offended, or put off by @KarandikarMihir's response.

@tomazy, should actually be added as a member of the organization, see #1236 Server Side Rendering. This is a huge contribution, and one significant reason (IMO) for RBP being in the #three position (rather than #two) in terms of GH stars. 

GH stars are important in achieving the project's goal of providing the "_best developer experience and a focus on performance and best practices_" to as many as possible. See Andrew Farmer's [React Project Starter List]([url](http://andrewhfarmer.com/starter-project/)).

Oh, and about that image, it's part of a "throw away project" true, but also one that is looked upon as providing a best practice example. Serving a 1.2 Meg image is _not_ a best practice!

So if there's a misunderstanding and upset here, let's patch that up, please and add @tomazy to the Member's list. The project will need him around if it is to support SSR!

**Comment by tomazy** [comment]
@gihrig  I'm not offended at all.  @KarandikarMihir comment actually made to go and look for a similar issue and I've found #907 It didn't know that you guys have a separate repo for the brand stuff and this image should probably be taken from there. I'll open a separate issue for it.

**Comment by KarandikarMihir** [comment]
@tomazy @gihrig I'm sorry, I had no intention of being rude or hurting anybody. We get many uninvited PRs (which is actually an indicator of how people love RBP and want to be a part of it), most of them are from newcomers. My reading is that [CONTRIBUTING.md](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md) being not very visible to everybody (because it's hidden away in `.github` folder) is one of the reasons why people don't follow the guidelines. So as a maintainer, I let people know that certain rules exist and following them will make it easier to maintain order.. My comment may have been blunt because I'm not a native English speaker and sometimes I lack the charm. I'm still learning that part. I apologize!

I admire and appreciate @tomazy's work on #1236 because I've been watching his work. Had I remembered that it's the same person, I'd not have written the comment because I know that _he's definitely not a newcomer._ **Furthermore, I realize that @tomazy deserves to be a member of RBP more than I do.** Welcome onboard! :smiley:  I'm always excited to work with people of such a great caliber and experience!

About the image- I totally agree with @gihrig. The larger image needs to be replaced by a smaller one.

> It didn't know that you guys have a separate repo for the brand stuff and this image should probably be taken from there.

I think only `README.md` has some assets that are being borrowed from brand repo. All of the other assets are locally hosted. See [Header component](https://github.com/react-boilerplate/react-boilerplate/tree/master/app/components/Header). So we'll just have to place the smaller image there.

**Comment by gihrig** [comment]
@tomazy @KarandikarMihir Thank you both for openly addressing my concerns - I _really_ wanted to be sure!

Glad to hear there's no rift brewing between two of this awesome community's equally awesome members!!! 💖

**Pull request closed without merging**
