### PR TITLE
Add CODEOWNERS file

### PR DESCRIPTION
**Pull request by vineyardbovines**
I've added a CODEOWNERS file, which might be pretty useful for us. [Article about code owners](https://github.blog/2017-07-06-introducing-code-owners/).

As time goes on, we can add more users to the file (or delegate parts of the app to certain users, if it makes sense to). Might just help delegation and drive some more collaboration! 

Also, feel free to suggest adding anyone else to this file now. I've added 4 of us so far (@julienben, @justingreenberg, @jwinn, and myself).

### CODE REVIEW

**Comment by julienben** [comment]
Great idea!

Perhaps we can add @Mensae since he wrote so many of the tests?

**Review by julienben — APPROVED** [review]

**Comment by vineyardbovines** [comment]
That's who else I had in mind @julienben

**Comment by jwinn** [comment]
@gretzky nice! I agree adding @Mensae makes sense. 👍

**Comment by JohnMostlyR** [comment]
Thanks!! 😊

**Comment by vineyardbovines** [comment]
@Mensae has been added! Will merge for now.

**Pull request merged**
