### PR TITLE
Revert "Adds jest -watch / jest -o in package.json"

### PR DESCRIPTION
**Pull request by justingreenberg**
Reverts react-boilerplate/react-boilerplate#2100

@blling please merge

### CODE REVIEW

**Comment by blling** [comment]
@justingreenberg Need to resart the failure CI :)

**Comment by blling** [comment]
ping @mxstbr, could you please resart the CI :)

**Comment by justingreenberg** [comment]
@blling should be rebuilding now :)

**Comment by blling** [comment]
Thanks! @justingreenberg  
I think i need to merge `master` into `dev` in a follow PR, i found there are some conflicts :)

**Pull request merged**
