### PR TITLE
Allow to pass additional parameters to the injected sagas

### PR DESCRIPTION
**Pull request by piuccio**
This PR needs some additional tests, but I wanted to have your feedback first.

In RBP 3.4 you would create your sagas as

```js
function* mySaga(action) {
   console.log(action); // { type: 'MY_ACTION' }
}
```

In 3.5 instead if you're using the `injectSaga` you end up with

```js
function* mySaga(whatsThis) {
   console.log(whatsThis); // it's the whole props object
   // turns out that the action is now the second parameter
}
```

As I'm updating my code, I really don't fancy modifying all my sagas to add an extra argument.

Moreover, I don't really like using props inside my saga, feels brittle. I thought the whole point of using actions was to pass parameters to a saga that doesn't have to depend on the props.

Finally, in another project based on 3.4 I need to access a firebase instance (irrelevant) and I want to have some sort of indirection. So instead of `import` the instance I need, I pass it as an argument to `injectSaga` inside `routes.js`. This option is now gone, there's no way to pass anything to the saga.

Getting to the point, I think it's handy to be able to pass stuff down the saga.

The proposed implementation works like this

```js
injectSaga({ key: 's1', saga: saga1 }); // same as the current dev branch
injectSaga({ key: 's2', saga: saga2, args: [] });
injectSaga({ key: 's3', saga: saga3, args: [{ banana: ' yellow'}] });

function* saga1 (props, action) {}
function* saga2 (action) {}
function* saga3 (fruit, action) {}
```

What do you guys think?

I don't like too much that there's no way to have `fruit` and `props` at the same time, so maybe there should be a flag to turn `props` on or off?

```js
injectSaga({ key: 'flag1', saga: saga1 }); // same as the current dev branch
injectSaga({ key: 'flag2', saga: saga2, props: false });
injectSaga({ key: 'flag3', saga: saga3, args: [{ banana: ' yellow'}], props: false });
injectSaga({ key: 'flag4', saga: saga4, args: [{ banana: ' yellow'}] });

function* saga1 (props, action) {}
function* saga2 (action) {}
function* saga3 (fruit, action) {}
function* saga4 (fruit, props, action) {}
```

For what it's worth, I don't think I'll ever use `props` in my saga

### CODE REVIEW

**Comment by gretzky** [comment]
travis build is failing -- if that could be taken care of, i'd be glad to look at this PR

**Comment by piuccio** [comment]
Sorry, I know it's failing, let me quote my first line

> This PR needs some additional tests, but I wanted to have your feedback first.

Can you please just comment on the message above first? I don't have time to work on a PR that will eventually be forgotten because it's not considered useful

**Comment by gretzky** [comment]
@piuccio Everyone here is doing this in their spare time. If you do not have time to work on a PR that you feel will be forgotten, then I'm unsure as to why you opened this PR?

The TravisCI build shows that it failed in the file you edited, so with that info it's hard for me to be able to give feedback on this PR that's failing from the beginning. When there is a working solution, I'll be able to give feedback. 

If you choose not to fix, I'll close this PR.

**Comment by piuccio** [comment]
@gretzky I fixed the tests

**Comment by piuccio** [comment]
thanks

**Pull request merged**
