### PR TITLE
Added Netlify deployment instructions

### PR DESCRIPTION
**Pull request by t3db0t**
corrected from previous PR

## React Boilerplate

Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.

**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.

Before opening a pull request, please ensure:

- [ ] You have followed our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md)
- [ ] Double-check your branch is based on `dev` and targets `dev` 
- [ ] Pull request has tests (we are going for 100% coverage!)
- [ ] Code is well-commented, linted and follows project conventions
- [ ] Documentation is updated (if necessary)
- [ ] Internal code generators and templates are updated (if necessary)
- [ ] Description explains the issue/use-case resolved and auto-closes related issues

Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)

**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [MIT License](https://github.com/react-boilerplate/react-boilerplate/blob/master/LICENSE.md).

### CODE REVIEW

**Review by justingreenberg — APPROVED** [review]

**Review by vineyardbovines — APPROVED** [review]
Looks great, thanks @t3db0t

**Review by jwinn — APPROVED** [review]
LGTM. Nice work!

**Comment by dominicwhyte** [comment]
I'm following these instructions but struggling with service workers. Should something be added to the instructions for how to deal with that and Netlify? This is the best info I've found so far https://www.netlify.com/blog/2018/09/21/international-service-worker-caching-awareness-day/ but still have not resolved the issue

**Comment by julienben** [comment]
Good point that's valid for all the deployment instructions. Ideally they would all explain how to disable caching for the service worker.

**Review by julienben — APPROVED** [review]

**Comment by julienben** [comment]
Thanks for your contribution @t3db0t!

**Comment by t3db0t** [comment]
Interesting, I didn't know about the service worker caching issue.

Thanks, and I'm glad I could help :)

**Pull request merged**
