### PR TITLE
Release v3.7

### PR DESCRIPTION
**Pull request by julienben**
Hello!

We've got lots of work in here including almost everything from #2327. Even though there are still things we'd like to do, I think it's time for a release just so we can have our master branch a bit more up to date. What do you think? Anyone disagree or have any additions that should really make it into this release?

If we wait to merge #2402 and #2396, this is a draft of our changelog:

- Upgrades to React v16.6, Babel v7, ESLint v5, styled-components v4 and more
- Many documentation updates including new section for forks (SSR, Electron, TypeScript)
- Bug fixes for generators, template app, scripts, and more
- Quick start - Clone to a named directory
- Migration from `react-router-redux` to `connected-react-router`
- Migration from `react-loadable` to `loadable-components`
- Switch from Yarn back to npm

I'll do some additional regression testing and write a full changelog with attributions before releasing.

### CODE REVIEW

**Comment by julienben** [comment]
Some of the things we'd like to fix but don't have time for in this release or things we may want to explore in the next version:
- All the issues with saga injections (#2021, #2121, #2266, #2314, potential solutions in #2399)
- Removing Immutable.js and replacing it with ???
- Maybe re-organizing the docs or publishing them to docusaurus or gitbook
- [Smart bundling](https://www.smashingmagazine.com/2018/10/smart-bundling-legacy-code-browsers/)

Feel free to suggest more. Will open this as an issue and invite PRs once we've released 3.7.

**Comment by julienben** [comment]
#2329 

Woot!! New RBP release coming to a computer near you!

**Comment by ngtan** [comment]
Thanks for your good work. I'm ready to upgrade my project.

**Comment by raisiqueira** [comment]
The "Migration" from the 3.6 for the 3.7 are go easy?

**Comment by ngtan** [comment]
> The "Migration" from the 3.6 for the 3.7 are go easy?

As I know, don't have an official document for upgrading, you have to do manually.

**Comment by julienben** [comment]
Exactly, no "automatic" migration possible as this is a boilerplate and not a dependency. It's in the docs [here](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/faq.md#how-to-keep-my-project-up-to-date-with-react-boilerplate). Do it manually by following all the changes in this PR. But only if you know what you're doing.

**Comment by justingreenberg** [comment]
👍 LGTM!

Note version needs to be updated in a couple spots prior to cutting release:
https://github.com/react-boilerplate/react-boilerplate/blob/master/package.json#L3
https://github.com/react-boilerplate/react-boilerplate/blob/master/internals/config.js#L7

**Comment by robertaird** [comment]
Pulling some more changes into a project, curious about one in particular. 
What's the thinking in changing initialState in app.js to an Immutable Map() here:
https://github.com/react-boilerplate/react-boilerplate/blob/7236a7b1685a9befabf68aef72dcecfa3111bdcc/app/app.js#L46
configureStore still runs fromJS() on initial state here:
https://github.com/react-boilerplate/react-boilerplate/blob/7236a7b1685a9befabf68aef72dcecfa3111bdcc/app/configureStore.js#L33
initialState's default value in configureStore is still a regular object as well. Should these be updated?

**Comment by justingreenberg** [comment]
@robertaird is correct, i actually noticed this as well.... imo, initial state should be bootstrapped as POJO and frozen in configureStore. there's really no need to create and pass an immutable object here. we can also remove Immutable import from app.js.

**Comment by julienben** [comment]
Makes sense. Will open a PR when I'm back in front of a computer. Unless someone wants to do it in the meantime.

**Comment by robertaird** [comment]
> Makes sense. Will open a PR when I'm back in front of a computer. Unless someone wants to do it in the meantime.

I can take care of it real quick while I'm still poking around the code.

**Comment by xeoneux** [comment]
Hey guys! Thanks for all the good work. 👍 
Sad that immer won't make it in 3.7 though

**Comment by gretzky** [comment]
Almost there @xeoneux !

**Comment by gretzky** [comment]
Its going off 🚀

**Comment by julienben** [comment]
@justingreenberg The config file disappeared with @gretzky's removal of the dll plugin.

**Pull request merged**
