### PR TITLE
Fix for errors after merging PR #2148

### PR DESCRIPTION
**Pull request by joggienl**
## Update Log

After creating a clone of the project, switch to the `dev` branch and run the `yarn run setup` and `yarn run clean` I noticed at least two things that went wrong. I wanted to contribute on these errors. The seem to fall after the merge for #2148 happened.

The errors resided inside the internals/templates directory.

I did not create an issue for this because the actual fix took me less time then writing an issue for it. If needed I could still create one of course!

**5/4/2018 update:**

The fix for `ERROR in ./app/app.js` got absolute due to PR #2164 getting merged.

### Tooling versions
- Node 9.9.0
- npm 5.8.0
- yarn 1.5.1
- Mac OS 10.13.3

### TypeError: (0 , _reducers.location) is not a function

Follow these steps to reproduce:

```sh
# Clone project
git clone git@github.com:react-boilerplate/react-boilerplate.git

# Go to project
cd react-boilerplate

# Checkout dev branch (1561d81)
git checkout 1561d81

# Run setup task, leave repository intact
yarn run setup

# Cleanup!
yarn run clean

# Run all tests
yarn run test
```

Two errors arise:

```
 FAIL  app/tests/reducers.test.js
  ● route reducer › should return the initial state

    TypeError: (0 , _reducers.location) is not a function

      at Object.<anonymous> (app/tests/reducers.test.js:11:35)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>

  ● route reducer › should handle the location_change action correctly

    TypeError: (0 , _reducers.location) is not a function

      at Object.<anonymous> (app/tests/reducers.test.js:19:35)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
```

Fixed with:  24b7f39

### ERROR in ./app/app.js
**5/4/2018 update:**
This error is obsolete since PR #2164 got merged to `dev`
Reverted with: 9180042

>Follow this step to reproduce:
>
>```sh
># Clone project
>git clone git@github.com:react-boilerplate/react-boilerplate.git
>
># Go to project
>cd react-boilerplate
>
># Checkout dev branch (1561d81)
>git checkout 1561d81
>
># Run setup task, leave repository intact
>yarn run setup
>
># Cleanup!
>yarn run clean
>
># Run project
>yarn run start
>```
>
>The following error arises:
>
>```
>✖ ｢wdm｣:
>ERROR in ./app/app.js
>Module not found: Error: Can't resolve './manifest.notjson' in >'/Users/jogchum/Workspaces/Sandbox/test/rbp-dev/app'
> @ ./app/app.js 37:0-58
> @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js
>```
>
>Fixed with: 0e1380c
>

### CODE REVIEW

**Comment by gretzky** [comment]
Thanks @joggienl, one thing I want to mention before I read is that you're using node v9, which is the latest bleeding edge version of node--- the recommended version is v8.11 I believe. If you can, switch to latest stable node (v8.11) just to check this stuff over in tandem, so we know none of it is attributed to node versions

**Comment by joggienl** [comment]
You mean the PR, or if this this also happens in node v8 as well? I can check that of course. I can't imagine that it is possible this differs because of the nature of the error's at hand (an export and a typo). But I can check :-).

The PR itself has been checked against v6, v7 and v8 (as per travis / appveyor configuration).

**Comment by joggienl** [comment]
I've run the code with and without the fixes with these versions:

- node v8.11.1
- npm v5.6.0

Results are the same, steps on the dev branch "fail" and with the fixes from this PR they don't.

**Comment by joggienl** [comment]
it is kinda out of scope of this pr, but wouldn't it be better to run the tests on this project also after an `npm run setup` and `npm run clean`?

**Comment by julienben** [comment]
I wrote #2148 so thanks for catching these! Both are my bad for not properly reflecting changes between app/ and internals/templates/.

About manifest.notajson, my hope is to switch to webpack-pwa-manifest (cf. #2164) so that manifest.json will be generated through webpack directly. More robust. This means the fix to internals/templates/app.js won't be necessary if #2164 gets merged.

The export in reducers.js is totally necessary though so I think this part should be merged.

**Comment by joggienl** [comment]
Hi @julienben! Thanks!
I did also see #2164. Would be nice indeed!

I thought about it as well indeed but since it was an easy (small) fix I decided to submit. It fixes current dev before #2164. I thought #2164 might take a bit longer to get in, because of review and such.
We'll see I guess!

**Comment by julienben** [comment]
Hey! #2164 was merged so could you edit this PR to contain only the reducers.js fix and then we can merge it?

**Comment by joggienl** [comment]
done!

**Comment by joggienl** [comment]
I've also updated the PR message a bit to reflect that the manifest.not(a)json file is not valid anymore.

**Comment by joggienl** [comment]
@julienben, @gretzky is everything complete this way? thanks!

**Comment by julienben** [comment]
Yup. If @gretzky doesn't get to it first, I can merge it as soon as I'm back in front of a computer on Sunday.

**Pull request merged**
