### PR TITLE
Add a memoized getComponent wrapper so that components do not get reloaded

### PR DESCRIPTION
**Pull request by trevorharwell**
## React Boilerplate

Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.

**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.

Before opening a pull request, please ensure:

- [x] You have followed our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md)
- [x] double-check your branch is based on `dev` and targets `dev` 
- [x] Pull request has tests (we are going for 100% coverage!)
- [x] Code is well-commented, linted and follows project conventions
- [x] Documentation is updated (if necessary)
- [x] Internal code generators and templates are updated (if necessary)
- [x] Description explains the issue/use-case resolved and auto-closes related issues

Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)

**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [MIT License](https://github.com/react-boilerplate/react-boilerplate/blob/master/LICENSE.md).

### CODE REVIEW

**Comment by trevorharwell** [comment]
As a side note to this PR, this resolves a lot of issues people might have with sagas being re-ran when navigating from dynamic route to dynamic route.

**Comment by trevorharwell** [comment]
Not sure how to resolve the build failure.  It failed on node v5 in a file that I didn't change.

**Comment by colek42** [comment]
"As a side note to this PR, this resolves a lot of issues people might have with sagas being re-ran when navigating from dynamic route to dynamic route."

We were having this issue.  This pattern solved it for us/.  Thanks @trevorharwell

**Comment by Andarist** [comment]
@trevorharwell Aint sure if this memoizing approach is the right way to do this. It might be worth doing in general, but not as the mentioned saga 'problem'.

There is a place for both saga scenarios - one which gets cancelled when you leave the route and one which will stay live forever for the application lifespan. Your solution kinda hides the symptom only and we probably should expose 2 different `injectSagas` APIs (for both use cases) and educate about them.

WDYT?

**Comment by yeluolei** [comment]
how can we fix this issue?

**Comment by gihrig** [comment]
> how can we fix this issue?

There has been a lot of discussion on this and several suggested solutions, but no consensus yet on the best way to go.

For starters, be sure that #1613 is not the problem.

Then check out #1554, #1545 and the issues it references for a thorough background on this issue.

**Comment by justingreenberg** [comment]
this issue should be resolved by #1746 :) would love any feedback! thank you very much again for your contribution! please let me know if you have any questions

**Pull request closed without merging**
