### PR TITLE
 feat(core): Add babel-plugin-transform-react-jsx-source

### PR DESCRIPTION
**Pull request by blling**
Add `babel-plugin-transform-react-jsx-source` to `dev`, which has been done by @justingreenberg but not in `dev`, see comment [here](https://github.com/react-boilerplate/react-boilerplate/pull/1969#issuecomment-339693446). [Here](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html#component-stack-traces) is why we need this plugin.

- [x] Add `babel-plugin-transform-react-jsx-source`.
- [x] Update engines[node >= 6, npm >= 5] in package.json.
- [x] Remove node v5 support from appveyor/travis.
- [x] Add 'internals/scripts' to the babel `development` env, because `internals/scripts` also needs `babel` at compile time.

### CODE REVIEW

**Comment by blling** [comment]
@justingreenberg if i do the wrong things, please correct me.
I actually did not find the two commits submitted branch~~

**Comment by justingreenberg** [comment]
@blling thanks :) CI is still failing due to es `import` in extract-intl script

since there is no transpilation step, extract-intl script should really be refactored to use commonjs like the rest of the scripts (i did this in https://github.com/react-boilerplate/react-boilerplate/pull/1969/commits/ca788bd18ca2090710e2b80889c06d9725c205b3#diff-06a205cb187ca03309b29239b4b414a6R18)

i have been swamped with work but there were other issues related to updating (update engines in package.json, remove node v5 support from appveyor/travis, updating some new eslint rules etc

thanks for your help @gretzky @blling :) hopefully i will have more time to devote after the holidays

**Comment by blling** [comment]
> updating some new eslint rules etc

@justingreenberg What is the new eslint rules? I think i can do it in the follow PR.

BTW:
Do you have some new idea  of `Logging intercept` and `ErrorBoundary`, if you have decided what to do, I will be happy to finish them.

**Comment by blling** [comment]
cc @gretzky @vigzmv

**Pull request merged**
