### PR TITLE
Clarify that Homepage is a container

### PR DESCRIPTION
**Pull request by akarve**
So that users don't look for it in `app/components`

### CODE REVIEW

**Comment by mxstbr** [comment]
Deploy preview failed.

Built with commit faed45953d9c12e7c22d89a84986951991881283

https://app.netlify.com/sites/react-boilerplate/deploys/5887dbe86686743e432de933

**Comment by akarve** [comment]
Hmm. According to the above all checks have passed, including https://deploy-preview-1517--react-boilerplate.netlify.com/

I don't have permission to access the netlify link you included.

**Comment by samit4me** [comment]
@akarve Are you still interested in getting this template changed? I too agree with the suggestions made by @gihrig, it will tell you precisely where to look as in the end they are all components, they just live in different directories.

**Comment by akarve** [comment]
@samit4me yes. i concur with suggestions and have modified the text. if preferred i can submit a clean PR branched from dev.

**Comment by akarve** [comment]
Apologies. I will have to get to this later.

**Comment by gihrig** [comment]
Why close this PR? Seems perfectly legitimate to me. Repoening...

**Comment by gihrig** [comment]
> Please rebase against dev branch.

Perfect 💯 

> This is the Home page!
>
> Found in 'app/containers/Homepage'.

Please work the path into your message, similar to above.

```
internals/generators/container/messages.js.hbs and
internals/generators/component/messages.js.hbs
```

These files need to be modified so generated containers and components have the updated description as well.

**Comment by samit4me** [comment]
Hi @akarve, that is great, looking forward to it.

As @gihrig said there is no need to open a new PR, pushing changes to this branch is fine, see [CONTRIBUTING](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#pull-requests).

If you want to open a new PR for whatever reason, please do so, but we will leave this open until you have! We would love  to see these changes merged in 👍

**Comment by KarandikarMihir** [comment]
@akarve Hi there! Can you push changes suggested in @gihrig's [comment](https://github.com/react-boilerplate/react-boilerplate/pull/1517#issuecomment-280942165). Looking forward to have these changes merged soon! :)

**Comment by akarve** [comment]
i'd love to but i'm crazy busy with work. i'm gonna donate to this wonderful project right now :) i don't know when i'll be able to get to this but in any case i don't want to hold things up.

**Comment by KarandikarMihir** [comment]
Closing because of inactivity. Also, not really critical for rbp. Feel free to reopen.

**Pull request closed without merging**
