### PR TITLE
Adding some tests

### PR DESCRIPTION
**Pull request by dennybiasiolli**
- tests: removing global-styles.js from coverage collect
- tests(FeaturePage): testing shouldComponentUpdate function
- tests(HomePage): testing if username prop is missing
- tests(ProgressBar): testing when route is not changing
- tests(Toggle): adding tests for empty values prop
- tests(store): adding missing tests
- tests(ProgressBar): adding missing tests

### CODE REVIEW

**Comment by KarandikarMihir** [comment]
@dennybiasiolli This is great!! Will get back to this in some time.

**Comment by KarandikarMihir** [comment]
@Dattaya We need this too!! Can you take a look?

**Comment by gihrig** [comment]
@dennybiasiolli Awesome! 💖  ✨

**Comment by dennybiasiolli** [comment]
I'm glad to help! 😉

**Pull request merged**
