### PR TITLE
Link for github org no longer 404

### PR DESCRIPTION
**Pull request by paulogdm**
Correcting my mistake on pull #2504 .

### CODE REVIEW

**Comment by julienben** [comment]
Thanks!

FYI, the old link isn't a 404 if you're a member of the react-boilerplate organization. I guess that's why it made it into the repo and no contributors caught it.

**Comment by paulogdm** [comment]
> Thanks!
> 
> FYI, the old link isn't a 404 if you're a member of the react-boilerplate organization. I guess that's why it made it into the repo and no contributors caught it.

Makes sense!

**Comment by julienben** [comment]
@gretzky @justingreenberg Who has access to the Netlify setup? It's not marking itself as successful even though the link works: https://deploy-preview-2505--react-boilerplate.netlify.com/

**Comment by gretzky** [comment]
I just triggered a deploy, let's see if it works.

**Comment by julienben** [comment]
I turned off Netlify success as a merge requirement until it's fixed.

**Pull request merged**
