### PR TITLE
Immer

### PR DESCRIPTION
**Pull request by julienben**
It might take a long time to reach a consensus in #2092 so after reading @mweststrate's [intro to Immer](https://hackernoon.com/introducing-immer-immutability-the-easy-way-9d73d8f71cb3) I gave a shot at migrating the sample app just so we can see what that would look like.

Immediate benefits:
- Immutable data without the need to use Immutable's custom data types
- Essentially no learning curve
- Removes over 50k from our builds
- Trivial to remove for anyone who doesn't want it. We could even add it as an option in the generators.

Thoughts? Opinions?

NOTE: Tests will fail. This is a WIP until we can agree on a direction.

### CODE REVIEW

**Comment by gretzky** [comment]
I guess I'm a bit confused as to why there's an immediate need to move away from Immutable if there doesn't seem to be a consensus on which direction we should head in? 

I don't use any immutable library in any of my own projects so I can't say much-- I only have one opinion: I don't agree about the 'no learning curve' piece. The syntax of this library seems pretty different from immutable (i.e `draft`?) and for anyone that uses this boilerplate as a part of their daily development, that's going to be a big difference.

Mostly I just don't want to assume our users learning curve. Although this is a production-ready boilerplate, I know it's used for reference quite a bit and Immutable is a big part of this project, it changes the way someone learns/builds/thinks about a redux store. I have a soft spot for people who learn React development from this boilerplate (it _really_ helped me back in the day) and experiencing Yet Another JS Library™ fatigue is real.

Every other bullet point I like and agree with tho 🎉 

If I'm the minority here, I have no problem going with this solution. It's tough because we aren't gaining a whole lot of traction with RFCs and immutability is a huge topic 🤷‍♀️

**Comment by mxstbr** [comment]
I didn't know there were RFCs—ping me Twitter when you have important RFCs and I'll share them with the wider React community? If there is one for Immutable.js, tweet it and I'll RT

**Comment by julienben** [comment]
It's #2092 but it may be better to start with a fresh one?

**Comment by julienben** [comment]
@gretzky If your main concern is the learning curve, maybe we should skip my next PR? I won't divulge what's in it but let's just say that it includes renaming the project to `angular-boilerplate` 😜😂

More seriously, I'm not trying to express a need to move to Immer, immediate or not. We can totally release 3.7 with Immutable and then any changes to store management can wait for a big 4.0 until we've had more time to discuss and agree.

At that time though, I would probably at least be suggesting a move away from Immutable.js. For several reasons that I'm happy to list (although I believe most of them have been discussed in #2092).

Btw, the main one is probably the huge learning curve associated with Immutable. IMO, a move to Immer would lower the overall learning curve of the project. (Take a quick look at the Immer intro and you'll see it has a tiny API.)

I also completely agree with you about this project being used as a reference and I also learned a TON from it. Seeing as the overall React community's consensus seems to be going towards seeing Immer as "the best way to do immutable state", perhaps "being a reference" means it would make sense for us to follow that trend. (Unless I'm not making sense?)

All that being said, I don't have a strong preference between Immer and another solution. @justingreenberg's suggestion of using [redux-immutable-state-invariant](https://github.com/leoasis/redux-immutable-state-invariant) to raise errors if data is mutated in dev is also a good one IMO (although it would be nice it we could find a maintained version).

In any case, I'm mostly trying to stimulate the discussion and as I said this can totally wait til the next version. :)

(Sorry I wrote so much!!)

**Comment by gretzky** [comment]
Happy to merge this whenever appropriate

**Comment by julienben** [comment]
> Happy to merge this whenever appropriate

@gretzky You're happy to switch to Immer? If so, I'll finish this branch soon.

**Comment by gretzky** [comment]
@julienben yeah I'd say so-- I still don't use immutability but I see the value. Removing it would be a bigger task imo. Take your time!

**Comment by julienben** [comment]
@gretzky I believe this is ready for review!

**Comment by gretzky** [comment]
All set!

**Pull request merged**
