### PR TITLE
Fix quickstart instruction for showing HMR in action

### LINKED ISSUE #1741: Quickstart example instructions are invalid.
In react-boilerplate/react-boilerplate/blob/master/docs/README.md, step 2 of the Quickstart guide tells you to edit the content of the "Features" button component in ./app/containers/HomePage/index.js to demonstrate HMR.

The label text for this button is now in the Header component and is stored as a FormattedMessage. 

I'm new to the react-boilerplate community, so I won't make a presumption as to the best solution, but the instructions should be changed to reflect the new file structure, or the components should be refactored so that the instructions are correct.

### PR DESCRIPTION
**Pull request by tiesmaster**
This fixes #1741. For me at least, this worked to get through the quickstart (changing the `messages.features` inside `message.js` didn't work).

Regarding linting, I don't know how the markdown needs to be wrapped, but this made sense for me.

### CODE REVIEW

**Comment by tiesmaster** [comment]
I forgot to change the base to the `dev` branch, so CI kicked off on that. I hope they pick up the change, without a lot of manual intervention.

**Comment by tiesmaster** [comment]
@gretzky Looks like the CI needs to be kicked off for TravisCI, and AppVeyor. Can you do that?

**Comment by vigzmv** [comment]
Hey @tiesmaster, can you rebase it with the dev branch and push  the commits as requested by @gretzky.
If it does not work, we can create a new PR.

**Comment by tiesmaster** [comment]
@vigzmv The branch is rebased on top of dev. What happened is that I created the PR on top of master (resulted in a big list commit that weren't mine). Then I changed the base to dev (resulting in only my commit), but the webhooks already triggered the CIs, with the wrong payload (at work we have the same thing with TeamCity, and that's a nighmare...).

I'll close the PR, and re-open it, that usually does the trick.

**Comment by vigzmv** [comment]
Thank you for your contribution @tiesmaster.

**Pull request merged**
