### PR TITLE
Move contributing doc to the right place

### PR DESCRIPTION
**Pull request by Aftabnack**
## React Boilerplate

This is mentioned in a [note](https://github.com/react-boilerplate/react-boilerplate/issues/1719#issuecomment-296346769). Not big enough to be an issue. 

Before opening a pull request, please ensure:

- [x] You have followed our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md). I am moving this.. :stuck_out_tongue: 
- [x] double-check your branch is based on `dev` and targets `dev` 

Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)

**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [MIT License](https://github.com/react-boilerplate/react-boilerplate/blob/master/LICENSE.md).

### CODE REVIEW

**Comment by Aftabnack** [comment]
Any update here?

**Comment by KarandikarMihir** [comment]
@gihrig This is related to [your comment](https://github.com/react-boilerplate/react-boilerplate/issues/1719#issuecomment-296346769). Looks good?

**Comment by KarandikarMihir** [comment]
Yeah. Let's give this a couple of days before we merge.

**Comment by KarandikarMihir** [comment]
Merging! ✌️

**Comment by gihrig** [comment]
just realized that [ISSUE_TEMPLATE.md](https://github.com/react-boilerplate/react-boilerplate/blob/dev/.github/ISSUE_TEMPLATE.md) and
[PULL_REQUEST_TEMPLATE.md](https://github.com/react-boilerplate/react-boilerplate/blob/dev/.github/PULL_REQUEST_TEMPLATE.md) need to be modified to point to the new location. Ooops! 😊

**Comment by Aftabnack** [comment]
Oh yeah. I didn't realize. Do you want me to make another PR?

**Comment by gihrig** [comment]
>Do you want me to make another PR?

Yes please! ✨

**Pull request merged**
