### PR TITLE
remove duplicated configuration code

### PR DESCRIPTION
**Pull request by juanda99**
All configuration code for DLL Plugin inside package.json file. 
More info: #1341

### CODE REVIEW

**Comment by mxstbr** [comment]
@datapimp why did we duplicate it in the first place?

**Comment by KarandikarMihir** [comment]
Maybe it was there as a fallback? Developers may play with package.json but it should not break DLL creation?

**Comment by KarandikarMihir** [comment]
@juanda99 Do you want to continue this? I saw you closed #1341.

**Comment by samit4me** [comment]
Thank you for taking the time to submit a PR ✨ Now closing this PR as the original issue has been closed and the PR is now getting stale.

**Pull request closed without merging**
