### PR TITLE
Adding missing svg-url-loader dependency to package.json

### PR DESCRIPTION
**Pull request by julienben**
I added svg-url-loader to the webpack plugins in #2164 but forgot to add it to package.json. This is a fix for that.

### CODE REVIEW

**Comment by julienben** [comment]
@gretzky Github won't let me suggest you as a reviewer but if you have a second, this is a VERY short one ;)

**Comment by gretzky** [comment]
@julienben I'm offended it won't let me review!

**Comment by gretzky** [comment]
@julienben all set buddy

**Comment by julienben** [comment]
Thanks!

**Pull request merged**
