### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by agamemnus**
One step in the quick setup is missing.

### CODE REVIEW

**Comment by KarandikarMihir** [comment]
@agamemnus Thanks for sending the PR. I think the wording should be something like-
> 2. Change the directory- `cd react-boilerplate`. 

That would suffice :)

**Comment by agamemnus** [comment]
Idk. It just doesn't feel complete that way. I reworded it slightly.

**Comment by KarandikarMihir** [comment]
@agamemnus Okay. Just mention the complete command (`cd react-boilerplate`) instead of `eg. cd`. Let's merge this in then!

**Comment by agamemnus** [comment]
I was just thinking someone might have a system that didn't have cd. That
might be an unfounded worry. Ok, I'll rework ot in a few hours to do it
like that. (I'm supposed to be asleep)

**Comment by KarandikarMihir** [comment]
@agamemnus Well it works on most of the platforms so let's not worry too much :smile:

**Comment by agamemnus** [comment]
Done.

**Comment by KarandikarMihir** [comment]
@agamemnus Awesome. Thank you for your contribution :sparkles:

**Comment by KarandikarMihir** [comment]
@react-boilerplate/core I inadvertently merged this without checking the base branch :disappointed_relieved: :cry: 

But thank god, it only changes the README.md. Just wanted to give you a heads-up.

**Pull request merged**
