### PR TITLE
Update FAQ with Styles getting overridden

### PR DESCRIPTION
**Pull request by samit4me**
An attempt to shine a light on potential style conflicts between classic CSS and `styled-components`. See #1589.

### CODE REVIEW

**Comment by eric-burel** [comment]
Hi, I think this is clear enough, however not everybody know the tricks to improve specificity in CSS. For example I did not know about the `&&` (my reflex would be to use `!important`).
Maybe adding an example could be good:

```javascript
const MyBlueDiv = styled.div`
    && {
        background-color: blue;
    }
`
```
```html
<!-- I will still be blue, whatever the class specified -->
<MyBlueDiv className="red" />
```

**Comment by samit4me** [comment]
Thanks for the feedback @eric-burel it's appreciated 👍 I've taken your suggestions and added examples, let me know what you think.

**Comment by eric-burel** [comment]
That's great! 

To make it perfect, I'd simply put the "1) Increase the specificity of the CSS you want to win" and "2) Import the CSS in the <head> of your index.html manually " in bold.

Also you could add a sentence before each of first solution example, like:
"I want the imported css to win:"
"Or, I want the styled-component css to win:"
because it's a bit unclear to have those two contradictory examples one after the other

**Comment by samit4me** [comment]
Thanks again @eric-burel both good points, updated as suggested.

**Comment by gihrig** [comment]
@samit4me It's looking really good ✨ 

The only thing I would add, is to include language specifiers in your code fencing for syntax highlighting.

e.g.
\```css

or 

\```javascript

See other examples higher up in the doc.

**Comment by samit4me** [comment]
💯 @gihrig, thank you

**Pull request merged**
