### PR TITLE
Fixed import ordering

### PR DESCRIPTION
**Pull request by VladBlow**
Just fixed import ordering

### CODE REVIEW

**Comment by VladBlow** [comment]
I don't understand why `continuous-integration/appveyor/pr` is canceled :(

**Comment by julienben** [comment]
It's a glitch in the way appveyor and github communicate but there's a build for your PR there. It'll be updated in a few minutes.

**Comment by VladBlow** [comment]
@julienben nice, thanks!

**Comment by julienben** [comment]
You do need to change your PR to point to the dev branch though. And please use the PR template in your description. I know it's a small change and it seems like overkill but it's still there for a reason.

**Comment by VladBlow** [comment]
## Changes

Just fixed import ordering, because eslint have an error

## React Boilerplate

Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.

**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.

Before opening a pull request, please ensure:

- [checkbox:checked] You have followed our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md)
- [checkbox:checked] Double-check your branch is based on `dev` and targets `dev` 
- [checkbox:checked] Pull request has tests (we are going for 100% coverage!)
- [checkbox:checked] Code is well-commented, linted and follows project conventions
- [checkbox:checked] Documentation is updated (if necessary)
- [ checkbox:checked] Internal code generators and templates are updated (if necessary)
- [ checkbox:checked] Description explains the issue/use-case resolved and auto-closes related issues

Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)

**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [MIT License](https://github.com/react-boilerplate/react-boilerplate/blob/master/LICENSE.md).

**Comment by julienben** [comment]
Thanks! There's still an issue though. You used the `master` branch as your base so what's happening here is you're also merging all the changes that are currently in `master` but not in `dev` into `dev`. To fix this, you need to checkout the `dev` branch from your fork and use that as the base for your `patch-1` branch. Does that make sense?

**Comment by julienben** [comment]
You should close this PR and reopen it with your new branch as the base.

**Comment by VladBlow** [comment]
@julienben yep

**Pull request closed without merging**
