### PR TITLE
Adds jest -watch / jest -o in package.json

### PR DESCRIPTION
**Pull request by shobhitchittora**
Closes: #2101

### CODE REVIEW

**Comment by blling** [comment]
En, I am sorry, not master, i will revert :sob:

**Comment by blling** [comment]
@justingreenberg Could i revert this merge? i am sorry, i do not notice the target branch is `master` :cry:

**Comment by gretzky** [comment]
I'd revert it and have it be pushed to dev instead

**Comment by justingreenberg** [comment]
@blling i took care of reverting this... no worries

@shobhitchittora please re-open again `dev` branch—thank you!

**Pull request merged**
