### PR TITLE
themePickerLimited

### PR DESCRIPTION
**Pull request by AlexandruFlorescu**
## React Boilerplate

Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.

**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.

Before opening a pull request, please ensure:

- [x] You have followed our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md)
- [x] double-check your branch is based on `dev` and targets `dev` 
- [ ] Pull request has tests (we are going for 100% coverage!)
- [x] Code is well-commented, linted and follows project conventions
- [x] Documentation is updated (if necessary)
- [x] Internal code generators and templates are updated (if necessary)
- [x] Description explains the issue/use-case resolved and auto-closes related issues

Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)

**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [MIT License](https://github.com/react-boilerplate/react-boilerplate/blob/master/LICENSE.md).

### CODE REVIEW

**Comment by AlexandruFlorescu** [comment]
Hey guys, 

Sorry for the complete lack of test coverage. I will add some tomorrow :) I'm not quite familiar with them but I'm happy to learn. I just wanted to get some feedback on this.

Hope this helps the project, I just added a flex-box under the header with the colors for the theme. I kept changes at minimum (or what I considered to be) 

I though about creating a new page for UI customization.

The page should contain multiple options for choosing between primary colors, secondary colors and a background pattern. I tried a few combinations locally and they look quite good. Any thoughts?

Thank you for your time and the opportunity to learn,
Alexandru

**Comment by blling** [comment]
I think RBP is no need theme picker for now, what you guys think?

**Comment by AlexandruFlorescu** [comment]
I agree. I have even given up on it. I would remove it myself but I don't know how.

**Comment by blling** [comment]
@AlexandruFlorescu OK, thanks for your contributing, then i will close it.

**Pull request closed without merging**
