### PR TITLE
Fix redux-saga link

### PR DESCRIPTION
**Pull request by hanloong**
Hey guys, was just reading through the introduction for the first time and noticed the redux-saga docs have moved. So the link has been updated.

Cheers :)

### CODE REVIEW

**Comment by gihrig** [comment]
Please read[ CONTRIBUTING.md ](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#pull-requests).

This has been reported (several times) and fixed in the `dev` branch.

But thanks for the effort anyway.

**Comment by KarandikarMihir** [comment]
@gihrig can we ship a hotfix for this? In master?

**Comment by gihrig** [comment]
That might make sense, but I would rather land a few other (doc related) PRs and ship 3.4.1.

Also. I recall @mxstbr wrote an article on "danger", an open source project monitor that checked and rejected PRs based a rule set. It can automatically reject PRs that don't meet basic requirements. Things like: not opened against dev, larger than some SLC and no issue mentioned, and anything else that can be scripted. I didn't save that URL 😢 

@mxstbr It this true? or am I dreaming?

**Comment by gihrig** [comment]
OK, I just found the [article](http://mxstbr.blog/2017/01/the-open-source-maintainers-best-friend/)

And [danger-js](https://github.com/danger/danger-js) looks really new, @mxstbr do you think it's solid enough to integrate in react-boilerplate?

**Comment by hanloong** [comment]
Ah my bad was just browsing `master` on github.com.
Glad its already fixed

**Comment by KarandikarMihir** [comment]
@gihrig Yeah, we can offload a lot of redundant work with `danger-js`. I just read that article. Looks like a cool tool to have. [styled-components](https://github.com/styled-components/styled-components/pull/380#issuecomment-273534304) is using it too!

**Pull request closed without merging**
