### PR TITLE
Add support for eslint-plugin-compat

### PR DESCRIPTION
**Pull request by julienben**
## React Boilerplate

What do you think of adding [eslint-plugin-compat](https://github.com/amilajack/eslint-plugin-compat)?

Basically, it's an ESLint plugin which checks the browser compatibility of your code.

It relies on a browserslist config (which I've added to package.json) and you can also tell it which features are polyfilled so it won't trigger errors for those.

Note that it uses data directly from caniuse.com and MDN so it should be very accurate.

### CODE REVIEW

**Comment by julienben** [comment]
Travis is failing for a super weird (and seemingly unrelated) reason :(

image

**Comment by julienben** [comment]
Ok Travis is failing everywhere so it's not related to this PR. Will investigate ASAP.

**Comment by gretzky** [comment]
Weird, I commented this in the other PR but maybe a dev merge might solve? With new testing lib in and all

**Comment by julienben** [comment]
Yup it's fixed! Ready for review ;)

**Comment by gretzky** [comment]
Cool !

**Pull request merged**
