### PR TITLE
missing word in docs > general > introduction

### LINKED ISSUE #1663: missing word in introduction.md
The word "as" is missing on line 55 to complete the sentence.
Please see PR

### PR DESCRIPTION
**Pull request by nk1tz**
Fixes #1663

### CODE REVIEW

**Comment by gihrig** [comment]
@nk1tz Good find, thanks for the fix! ✨ 

Please rebase against `dev` branch.

See [CONTRIBUTING.md](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#pull-requests)

**Comment by KarandikarMihir** [comment]
Oh god, I think I messed it up. :sweat_smile: @nk1tz Sorry, would you mind sending a fresh PR with base as `dev`?

**Comment by KarandikarMihir** [comment]
@nk1tz Could you please send a new PR? Sorry for the inconvenience..

**Comment by KarandikarMihir** [comment]
Closing in favor of #1789.

**Pull request closed without merging**
