### PR TITLE
AWS deployment docs corrected and improved

### PR DESCRIPTION
**Pull request by Can-Sahin**
Updating AWS deployment docs and adding Cloudfront for HTTPS and remarking on important gotchas.

Following the issue https://github.com/react-boilerplate/react-boilerplate/issues/2764#issuecomment-546490298

### CODE REVIEW

**Comment by julienben** [comment]
Thanks for the PR @Can-Sahin! Looks good!

Just a question: Must the user upload the build folder manually? There's no CLI tool or something else to make the process more convenient?

**Comment by Can-Sahin** [comment]
There is a cli and I have [script](https://gist.github.com/Can-Sahin/d7de7e2ff5c1a39b82ced2d9bd7c60ae) for it. Using `aws-cli`. I can reference this gist if its ok or just copy paste core lines into the docs ?

**Comment by julienben** [comment]
A link/reference sounds good to me! I just think we can do better than telling the users to manually upload their build folder.

**Comment by Can-Sahin** [comment]
Ok added a reference to my gist.

**Review by julienben — APPROVED** [review]
Nice job @Can-Sahin !

**Pull request merged**
