### PR TITLE
feat(internals): Improve generator warnings  (#1462)

### PR DESCRIPTION
**Pull request by Necmttn**
fixes the conflict at (#1407, #1462) @gihrig  please check. 

Documented in [gotchas.md](https://github.com/react-boilerplate/react-boilerplate/blob/dev/docs/general/gotchas.md#load-reducers-optimistically).

### CODE REVIEW

**Comment by gihrig** [comment]
@Necmttn There are lint errors when run against `dev` branch. Please run `npm test` on your fork and correct those.

**Comment by KarandikarMihir** [comment]
The message could be improved. We need something concise but descriptive at the same time 😅

> ⚠️ Please pass this reducer explicitly to combineReducers in reducers.js if you don't want to inject it asynchronously.

Or

> ⚠️ Please pass this reducer explicitly to combineReducers in reducers.js if you want to use it out of the box.

Or something on similar lines. Perhaps someone with prowess in English can suggest better wording?
@mxstbr We could make use of your inputs on this one.

**Comment by gihrig** [comment]
I would suggest a concise one-liner, since this is going on an already busy screen.

> Remember to add this reducer to combineReducers in app/reducers.js

**Comment by KarandikarMihir** [comment]
@gihrig Yup! This one's better.

>Remember to add this reducer to combineReducers in app/reducers.js

**Comment by gihrig** [comment]
@Necmttn 

I vote for:

1. Message in terminal when running generator:

`⚠️ Remember to add this reducer to combineReducers in app/reducers.js`

2. Add the same text as a code comment at the top of the generated `reducer.js`.

**Comment by KarandikarMihir** [comment]
I second @gihrig.

**Comment by KarandikarMihir** [comment]
Umm. 

>⚠️ Remember to add this reducer to combineReducers in app/reducers.js


But it doesn't quite say that you don't _HAVE TO_ add this if you're going to go for asynchronous injection. I'm sorry I'm being a pest here.

**Comment by gihrig** [comment]
>  I'm sorry I'm being a pest here.

Yes, you are 😄 

⚠️ Not loading in a route?, Add to app/reducers.js: combineReducers. Ref #1407.

Better still, make this [#1407Comment](https://github.com/react-boilerplate/react-boilerplate/issues/1407#issuecomment-271066646) a gotchas.md entry and reference that.

**Comment by KarandikarMihir** [comment]
😅 😄 This better!! It shouldn't create any confusion for the users. Thank you, @gihrig 

> Better still, make this #1407Comment a gotchas.md entry and reference that.

I'll do that.

**Comment by OsmanMesutOzcan** [comment]
I have a custom prompt that seamlessly warns without the need for another confirmation. You can check it out. https://github.com/OsmanMesutOzcan/inquirer-confirm-warning

**Comment by KarandikarMihir** [comment]
@OsmanMesutOzcan Hi! You've got a cool tool there. But using that would mean adding one more dependency in the project. We generally tend to avoid that.

Furthermore, we just want to display one line, without needing any confirmation from the user. So there's no point in adding interactivity here. Thanks for the suggestion, though :)

**Comment by OsmanMesutOzcan** [comment]
@KarandikarMihir The current solution actually needs an extra confirmation. Thats why i suggested an option. You can just show an extra line using it.

**Comment by Necmttn** [comment]
@gihrig 
I agree with you. 
I just made changes accordingly. any other suggestions  or good to go ?

**Comment by KarandikarMihir** [comment]
@Necmttn Hi. Isn't it 

> :warning: Not loading in a route?, Add to app/reducers.js: combineReducers. Ref #1407.

As per [this comment](https://github.com/react-boilerplate/react-boilerplate/pull/1523#issuecomment-275830051)

**Comment by gihrig** [comment]
@Necmttn I agree with @KarandikarMihir regarding warning text.

@KarandikarMihir Will need to complete that [gotchas.md entry](https://github.com/react-boilerplate/react-boilerplate/pull/1534#issuecomment-276139672) so it can be referenced in a code comment.

**Comment by gihrig** [comment]
@Necmttn Re: the conflict, it's OK to remove `yarn.lock` from the PR. It has no bearing on the proposed changes.

**Comment by Necmttn** [comment]
@gihrig 
for remove file from PR i follow, http://stackoverflow.com/a/9498304/6942552
i hope is the correct way to do it.

**Comment by gihrig** [comment]
>for remove file from PR i follow, http://stackoverflow.com/a/9498304/6942552
>i hope is the correct way to do it.

Seems to have worked 😄 

@Necmttn I closed/opened the PR (to force a rebuild) in hopes the AppVeyor failure was a transient issue.

Question though, what's your dev platform? Mac, Windows, Linux?

**Comment by gihrig** [comment]
@KarandikarMihir I'm really tied up with work ATM, can you check this out?

**Comment by gihrig** [comment]
Working with this I find the prompt to be a likely source of confusion:
image

How are 'Y' and 'N' answers different? Of course there's no difference.

I think I would prefer to eliminate the prompt, thinking the yellow warning and the code comment are sufficient to draw attention without adding an extra keystroke to the generate process.

Alternatively the prompt could be changed to simply 'OK'.

Or, more complex (probably best), ask if the developer wants to have the reducer wired up and do so if requested.

Thoughts?

**Comment by KarandikarMihir** [comment]
@gihrig Same here. I had tested this but couldn't find time to point it out here. I agree with you. It should say 'OK' or nothing really, if that's possible.

@Necmttn Can you please make these changes?

**Comment by Necmttn** [comment]
the ``(y/N)`` is default value coming from [Inquirer]( https://github.com/SBoudrias/Inquirer.js/#confirm---type-confirm)   and this is the most simple prompt they have in the library.

I don't know any other way around.

**Comment by gihrig** [comment]
> the (y/N) is default value coming from Inquirer

@Necmttn Can we just not use Inquirer and use Chalk to color the message?

**Comment by Necmttn** [comment]
@gihrig , now it's only show's the message without ``(y/N)`` but still you need to press enter for next prompt.

**Comment by gihrig** [comment]
@Necmttn Can we remove the need for the "mysterious" enter?

The page content is short enough that it won't be missed.

**Comment by Necmttn** [comment]
Alternative-)
image
if we do like this.  the location of (y/N) is changing. but we don't need to press ``"mysterious" enter`` but i think this will cause miss direction the user.  because it will be shown even user doesn't want reducer. 

```
{
    type: 'confirm',
    name: 'wantActionsAndReducer',
    default: true,
    message: `Do you want an actions/constants/selectors/reducer tuple for this container?
  ${chalk.yellow('⚠️ Not loading in a route?, Add to app/reducers.js: combineReducers. Ref #1407.')}`,
  },
```
With Current Version we only show warning when user want to add reducer.  
a fixes can be we can add ``[ENTER] `` end of string so UX could improve.

image
something like this.

**Comment by gihrig** [comment]
@Necmttn 

 - I don't understand the color change (compared to [here](https://github.com/react-boilerplate/react-boilerplate/pull/1523#issuecomment-279830518)) shown in your last post. Is this a proposed change, or just the way it appears on your terminal?

- > With Current Version we only show warning when user want to add reducer.
a fixes can be we can add [ENTER] or [Okay ?] end of string so UX could improve.

Is there no way to simply display the message only if the user wants a reducer without making it an additional prompt?

If that's true a suitable prompt might be "OK" or "Got It!" But from a UX perspective, it's just warning requiring on user action.

**Comment by Necmttn** [comment]
@gihrig  it's just how it's appears on my new terminal settings 😄 
there's no way unless, inquirer.js supports [Warn] prompt ( so far I know )

`` Got It! `` sound cool to me.

**Comment by KarandikarMihir** [comment]
@Necmttn This is one of the long-pending PRs. Do you think we can make it to the finish line? :smile: Let me know.

**Comment by KarandikarMihir** [comment]
Closing this due to inactivity. Feel free to reopen.

**Pull request closed without merging**
