### PR TITLE
docs(maintenance): Create dependency update doc

### PR DESCRIPTION
**Pull request by gihrig**
Create an official "Update Dependencies" doc and add link to README.md

These are the notes I've assembled while doing dependency updates. I've applied some quick and dirty markdown to make it at least readable. Feel free to modify and ask questions as needed.

Use Github search `is:pr author:gihrig update deps ` to see previous examples.

### CODE REVIEW

**Comment by gihrig** [comment]
@KarandikarMihir This looking really excellent! ✨ 

I have one request (Github won't allow me to make change requests?). Please make some mention of "pinned" version numbers, the project does not use "^", "~", etc., and these should be removed if present. Possibly reference #598.

Otherwise 👍 👍 👍

**Comment by KarandikarMihir** [comment]
@gihrig Done!

**Comment by gihrig** [comment]
@KarandikarMihir It has my LGTM (even though that's technically "illegal") 😄

**Comment by KarandikarMihir** [comment]
@gihrig Alright :smiley: Let's :shipit:

**Pull request merged**
