### PR TITLE
feat(internals): Add prettier integration

### LINKED ISSUE #1945: RFC: Prettier
i'm surprised nobody has brought this up yet... it's been a game changer for my team. would be nice to integrate with #1711 husky pre-commit hooks. imo this is a no-brainer, kinda wish it shipped with v3.5. maybe we can tighten up the releases and cut another minor in the next couple of weeks

### PR DESCRIPTION
**Pull request by blling**
JG: resolves #1945

Replace #2083

This PR complete the following task:
- [x] Add prettier integration.

@azz's suggestions:
Use the `plugin:prettier/recommended` ESLint config: https://github.com/prettier/eslint-plugin-prettier#recommended-configuration
`$ yarn add --dev eslint-plugin-prettier eslint-config-prettier`
```json
// .eslintrc.json
"extends": ["plugin:prettier/recommended"],
 ```
And just add one custom option now:
```json
"prettier": {
  "singleQuote": true
},
```

And add  `lint-stage` as follows:
```json
  "lint-staged": {
    "*.js": [
      "prettier --write",
      "lint:eslint",
      "stylelint",
      "git add"
    ]
  },
```
`git add` in the `lint-stage` will add the correct file:)

- [x] Run prettier on the entire codebase and fix problems after run prettier.

Two main changes:
1. Add `stylelint` rules:
```javascript
    "rules": {
      "rule-empty-line-before": null,
      "declaration-block-semicolon-newline-after": null
    }
```
2. Replace `eslint-disable-line` to `eslint-disable-next-line` in some special lines. 

- [x] Fix generate CI failure.

Add `prettier` action for plop, in order to format the js file after generated.

### CODE REVIEW

**Comment by gretzky** [comment]
@blling can you resolve the conflicts here?

**Comment by blling** [comment]
If #2113 merged, the conflicts will go away, I will wait for #2113 :)

**Comment by blling** [comment]
Prettier is aready land on master, so i close it. Thanks @julienben .

**Comment by julienben** [comment]
@blling Sorry I didn't cherry pick from this branch. I tried it but it became messy with the other changes in the v3.6 branch.

Also, I took a look at what you did with plop and prettier and think this was a simpler solution: https://github.com/react-boilerplate/react-boilerplate/commit/6c4001270293de66871d360f27d21e469d3aeaf9

Lmk if you think I missed something though.

**Pull request closed without merging**
