### PR TITLE
docs: Fixed styled-components Supported CSS link

### PR DESCRIPTION
**Pull request by JulienMelissas**
The [previous link](https://github.com/styled-components/styled-components/blob/master/docs/css-we-support.md) took you to a page asking to update bookmarks, so I've changed the link to the new one.

Hope it's okay to clear out the PR template since this is so small.

### CODE REVIEW

**Comment by blling** [comment]
Could you also correct these like places?
https://github.com/react-boilerplate/react-boilerplate/pull/2096/commits/e20809c8de761224165691f549fdd3fad2f63f1d#diff-aaf37926be338d984339b90b0bd3418eL123

**Comment by JulienMelissas** [comment]
@blling - sorry I'm not sure exactly what you mean, there's no links there. Did you mean to update it with the syntax in their docs like this?
```
use: [
  { loader: "style-loader" },
  { loader: "css-loader" }
]
```

**Comment by blling** [comment]
I am sorry, i did not notice that you purpose to merge into `react-boilerplate:master`, please change to `react-boilerplate:dev`

**Comment by blling** [comment]
I think you should use rebase your `patch-2` to `dev` :)

**Comment by JulienMelissas** [comment]
@blling I'm working on it right now 👍 , is it acceptable to do a force-push?

**Comment by blling** [comment]
force-push is ok, i think.

**Comment by blling** [comment]
Everything looks good now, i will merge this after CI pass, thanks!

**Comment by JulienMelissas** [comment]
Sounds good - thanks for the clarification on the proper branch, sorry about that.

**Comment by blling** [comment]
That is ok, look forward to your more contributions :)

**Pull request merged**
