### PR TITLE
Docs update: ts repo links added

### PR DESCRIPTION
**Pull request by Can-Sahin**
TypeScript fork added to the docs, discussed  at #2351

### CODE REVIEW

**Comment by julienben** [comment]
Hey @Can-Sahin,

Take a look at #2372. I created a section specifically for forks. I'd be happy to add yours there too.

Either way, I don't think forks should be linked like this from the 2 main README files in the repo. It would be a mess if we'd also added the Electron and SSR forks there.

**Comment by Can-Sahin** [comment]
Ahh ok @julienben  I have just realised that. Then I'm gonna link repo to the Forks section only. What about PR to master? In the discussion it is said fine but there is no Forks section in the master

**Comment by julienben** [comment]
My hope is to release a new version very soon so we won't need a PR to master.

If you don't mind, please wait til someone approves #2372 and it's merged so that you can make your changes to the [forks README file](https://github.com/react-boilerplate/react-boilerplate/blob/29f62a1ba344b0699aa94568e09263a1c387d9d1/docs/forks/README.md) directly. Or I can take care of it for you myself. As you wish.

**Comment by Can-Sahin** [comment]
Ok. Closing this then. I will wait till forks readme file merges than I will PR to that only. No master PR. Once the new version is released I will mostly like sync the TS repo with it. Thanks for the work...

**Pull request closed without merging**
