### PR TITLE
Dev catchup

### PR DESCRIPTION
**Pull request by julienben**
Had to resolve the conflicts in a separate branch since dev is protected. If my git-fu is correct, this should work.

### CODE REVIEW

**Comment by davidthornton** [comment]
This appears to get `dev` up to speed, while also passing CI; assuming this gets merged, I'm keen to rebase #2238 on top of it! 🎉

**Comment by gretzky** [comment]
Ah, I guess I lied, there are conflicts but tbh I don't see any on my end? @julienben let me know what you see

**Comment by julienben** [comment]
No conflicts ;)

It's just that it can't be rebased but it can be squashed and merged.

**Comment by julienben** [comment]
I'm not sure why but if you try to compare master and dev, there's a huge diff:

https://github.com/react-boilerplate/react-boilerplate/compare/dev?expand=1

Will look into it tomorrow. The dev branch might not be ready after all.

**Comment by julienben** [comment]
@gretzky @mxstbr Are there any reasons why we couldn't just delete `dev` and recreate it from `master`?

**Comment by julienben** [comment]
@gretzky Any thoughts on this? We need a clean dev branch 😬

**Comment by gretzky** [comment]
@julienben I'll take a look at that diff and see what's up

**Comment by julienben** [comment]
How does one celebrate Independence Day with a clear conscience when our dev branch is in such chaos?? 😲

J/k of course! Take your time!

**Pull request merged**
