### PR TITLE
More declarative component tests using jest-dom/extend-expect

### PR DESCRIPTION
**Pull request by tigranpetrossian**
This is a proposal to use [jest-dom](https://github.com/testing-library/jest-dom) matchers in component tests, thus making assertions more declarative and readable:
```diff
- expect(component.classList).toContain(classname)
+ expect(component).toHaveClass(classname)

- expect(component).not.toBeNull();
+ expect(component).toBeInTheDocument();

// etc.
```

For now I rewrote the basic link component test accordingly to see what you folks think about this. Also refactored the existing `renderComponent` function to return the element directly.

If approved, I can refactor the remaining components (wherever it would make sense) either all within this PR or gradually if it gets too large.

## React Boilerplate

Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.

**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.

Before opening a pull request, please ensure:

- [x] You have followed our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md)
- [x] Double-check your branch is based on `dev` and targets `dev` 
- [ ] Pull request has tests (we are going for 100% coverage!)
- [ ] Code is well-commented, linted and follows project conventions
- [ ] Documentation is updated (if necessary)
- [ ] Internal code generators and templates are updated (if necessary)
- [x] Description explains the issue/use-case resolved and auto-closes related issues

Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)

**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [MIT License](https://github.com/react-boilerplate/react-boilerplate/blob/master/LICENSE.md).

### CODE REVIEW

**Comment by julienben** [comment]
@tigranpetrossian I am 100% on board with this change and I'm fairly sure anybody else who looks at this will agree.

Just a tip if I may: we also have the template app, the docs and the generators to synchronize with the demo app. 

Let me know if you'd like any help at all and thank you for another top notch contribution!

**Comment by tigranpetrossian** [comment]
@julienben Cool! The main concern right now is not letting this PR grow too large, I'll play with this a bit too get the sense of the scale and post an update.

**Comment by julienben** [comment]
Personally I don't mind a large PR if it's mostly propagating an improvement throughout the whole repo. I'd prefer it to be in one large but complete PR rather than spread out.

**Comment by tigranpetrossian** [comment]
This should be good to go. Along with just replacing existing matchers with `jest-dom` it made sense to do few more tweaks while I was at it:

* Replace manual DOM queries with native querying methods from `testing-library` where it was possible. This aligns better with `testing-library`'s philosophy of trying to replicate what a real user would see: [Which query should I use? · Testing Library](https://testing-library.com/docs/guide-which-query)
* Replace few remaining traces of `react-test-renderer` with `react-testing-library` in snapshot tests.

Generators don't need to be updated; the changes from this PR aren't affecting default tests.

Documentation in is current state doesn't seem to need additions as well.

Speaking of documentation, I feel like the [testing-library](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/testing/component-testing.md#react-testing-library) portion of it could be improved by deprioritizing snapshot tests and mentioning that `styled-components` tests are mostly there for demo purposes, but that probably should go into a new PR.

**Comment by julienben** [comment]
Thanks for all your work on this @tigranpetrossian! Will review asap.

Strangely, Travis hasn't triggered a build for this PR. Will look into it.

**Comment by julienben** [comment]
Travis isn't triggering a build for this PR and I can't find a fix so we can't merge directly into dev from here. Instead I created a separate branch (called jest-dom-extend-expect). I'll merge this PR into it and then open a PR from the new branch into dev.

FYI Github should still be able to count the contribution as coming from you. You're also welcome to submit a PR adding yourself as a contributor. (See [here](https://github.com/react-boilerplate/react-boilerplate#contributors).)

**Comment by tigranpetrossian** [comment]
Thanks! I suspect this is because the PR was a draft initially. It should've still triggered after marking it as ready; probably a bug on their end.

**Comment by julienben** [comment]
Ah yes good point!

**Comment by julienben** [comment]
Travis just never registered this as a PR when it was draft and the relevant web hook probably wasn't triggered when changing it from draft to regular PR.

**Pull request merged**
