### PR TITLE
React routerv4/ssr. Merged functionality of #1745 and #1236

### PR DESCRIPTION
**Pull request by ax-hd**
## React Boilerplate
Since there was a vote to merge either react router v4 or server side rendering, I was looking to implement both in this boilerplate. I have merged code from both the commits and got React router v4 working with Server side rendering, solving errors as I encountered them. I know there is bit of work to be done with my pull request. Can someone check this work and tell me what I need to do to get this merged. I have not written corresponding scripts and test (because I dont yet know how), I can learn and implement them. Please suggest other changes to be done. 
To run:
npm run ssr:clean
npm run ssr:generate
npm run start

Sometimes npm run start needs to be done twice. I need to fix it.

### CODE REVIEW

**Comment by TheRusskiy** [comment]
@ax-hd this does not actually render components containers on server, I think it is because inside AsyncRoute containers are loaded like promises, and SSR doesn't really wait for these import promises to be resolved.
If you disable JS and load a page you are gonna see that imported components are not rendered

**Comment by leifdalan** [comment]
@TheRusskiy Yes, I noticed that too. The header and footer render but the inner components don't, because they are using Async Component, which relies on lifecycle methods that react SSR does not execute. 

I read this article a while back, it may prove useful, particularly the piece where you essentially have different require statements for server/client for your component containers: https://github.com/react-boilerplate/react-boilerplate/pull/1913

**Comment by TheRusskiy** [comment]
I used @tomazy 's ssr branch of this repo and for lazy component loading on server I used https://github.com/seeden/babel-plugin-dynamic-import-node-sync
but you would have to be careful to make sure that import is not used as a promise anywhere on the server

**Comment by ax-hd** [comment]
OK, I will look into it. Thanks for reporting. @TheRusskiy

**Comment by blling** [comment]
@ax-hd I think this PR is repeat of  #1236, should we close this one?

**Comment by blling** [comment]
Closing as stale, more discussion please see #1236.

**Pull request closed without merging**
