### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by MariusRumpf**
This PR upgrades the dependencies to the latest version. ngrok v3 update is not included, since it requires node>=8.3.0 . Options changed for the packages `lint-staged`, `eslint-plugin-jsx-a11y` and `node-plop`.

Vendor prefixes have been remove from the `LoadingIndicator/Cirlcle.js` file. This should not be necessary and been taken care of by styled-components as stated in the Readme.

Fixes have been applied from upgraded eslint and stylelint.

### CODE REVIEW

**Comment by MariusRumpf** [comment]
The travis node v6 build has very slow and finally stuck for no apparent reason and has to be restarted.

**Comment by mxstbr** [comment]
Deploy preview for *react-boilerplate* failed.

Built with commit e6cd034f526a3d8ba4070ceec12d4fc8fd2d3b53

https://app.netlify.com/sites/react-boilerplate/deploys/5a9be4237b6ee87e1288c67a

**Comment by MariusRumpf** [comment]
Waiting for https://github.com/react-boilerplate/react-boilerplate/pull/2146 to fix the node v6 build timeouts. That should fix travis ci. Netlify worked before and I am unsure if it is related to my last commit with minor version changes. Will have another look at it if travis is fixed. Experienced similar and same issues as mentioned in https://github.com/react-boilerplate/react-boilerplate/issues/2127 here.

**Comment by julienben** [comment]
Closing this for lack of activity and build still broken

**Pull request closed without merging**
