### PR TITLE
Replacing Enzyme with react-testing-library

### PR DESCRIPTION
**Pull request by julienben**
Merged @Mensae's work from #2452 into a local branch so we can fix any remaining issues here directly.

@Mensae's commits so far:

* [Fix] Fixing issue were not all attributes are passed as required by 'containers/RepoListItem/IssueIcon' that wraps this component, according to test case 'should adopt any attribute'

* Replacing 'enzyme' as testing utility with 'react-testing-library'.

* Adapting the generator test templates for components and containers to use react-testing-library.

* Adapting the testing documentation for use with react-testing-library

* [Doc] Adding comments to the test templates to make clear that the standard snapshot test is skipped by default.

* [Doc] Fixing a typing mistake.

* Adding cleanup() from react-testing-library to tests that were missing it.

* Adding some words to point out that the implemented tests in the example app deliberately show implementation variations in order to act as a guidance.

### CODE REVIEW

**Comment by mxstbr** [comment]
Deploy preview for *react-boilerplate* failed.

Built with commit f339385a166a5e689e0512a514431e05fbcc6940

https://app.netlify.com/sites/react-boilerplate/deploys/5bf3fc23daeb0a718f6b772d

**Comment by julienben** [comment]
@Mensae Are you still interested in merging this into the repo? There's not a ton of work there IMO but it does need some updates (given latest changes) and some documentation work. What do you think?

**Comment by Mensae** [comment]
Hi @julienben Yes, certainly. I'll work on the needed updates. What changes would you like to see in the documentation?

As I make use of snapshots in some of the rewritten test cases it will still fail on Travis due to the French language injection as I mentioned earlier. I purposed a fix for this [here](https://github.com/react-boilerplate/react-boilerplate/pull/2473)

**Comment by Mensae** [comment]
Didn't mean to close it

**Comment by julienben** [comment]
`component-testing.md` definitely needs an update. And `introduction.md` needs a one line fix.

Regarding #2473, sorry it's stayed untouched for so long! Will dig in to it asap.

**Comment by Mensae** [comment]
@julienben I just opened a new [PR](https://github.com/react-boilerplate/react-boilerplate/pull/2589). Reason is that the updated `styled-components` package caused some snapshots test to fail so they had to be updated. I also updated the `react-testing-library` and `jest-dom` to the current versions and updated `introduction.md`.

With regard to [component-testing.md](docs/testing/component-testing.md), would you mind to add some comments as to what you'd like to see different?

**Pull request closed without merging**
