### PR TITLE
fix(tests): Replace sinon restore

### LINKED ISSUE #1502: sinon.restore is deprecated - need to refactor
This will become an issue when sinon 2.0.0 is released.

Warning: app/components/ProgressBar/tests/ProgressBar.test.js
console.info node_modules/sinon/lib/sinon/util/core/deprecated.js:27
sinon.restore is deprecated and will be removed from the public API in a
future version of sinon. (20+ others)

Observed in test console during test phase of npm test
sinon 2.0.0-pre → 2.0.0-pre.5 <--- rolled back

To reproduce:
confirm #1501 has been merged
checkout current `dev` branch
Update sinon 2.0.0-pre → 2.0.0-pre.5
npm test

Boilerplate 3.4+ `dev` branch (ad871d7a1b70cec5b365fdc30eb86ee7e189158f)
Node 7.4.0
npm 4.1.1
yarn 0.19.1
Mac OS 10.11.6
Chrome 55.0.2883.95 (64-bit))

### PR DESCRIPTION
**Pull request by KarandikarMihir**
Fixes #1502. 

@gihrig I had to install `sinon@2.0.0-pre.5` to see those deprecation warnings.

### CODE REVIEW

**Comment by gihrig** [comment]
@KarandikarMihir This looks great, except that it puts the fix before the problem (sounds good though, doesn't it?) 😉 

> @gihrig I had to install sinon@2.0.0-pre.5 to see those deprecation warnings.

From #1502 
>To reproduce:
confirm #1501 has been merged
checkout current dev branch
Update sinon 2.0.0-pre → 2.0.0-pre.5
npm test

This PR probably creates many merge conflicts with #1501 (deps update) in `webpack.dev.babel.js` and `package.json`. 

For that reason we should get #1501 merged first. It includes no breaking changes AFAIK. Please review #1501.

**Comment by KarandikarMihir** [comment]
> This looks great, except that it puts the fix before the problem

:smile: 

FYI, I pulled in #1501 before making any changes. So it shouldn't create any merge conflicts if we merge #1501 first and then this.

**Comment by gihrig** [comment]
> FYI, I pulled in #1501 before making any changes. So it shouldn't create any merge conflicts if we merge #1501 first and then this.

Sounds good, I guess the only way to find out is to merge #1501 and update this PR. Given that sequence it has my LGTM.

**Comment by gihrig** [comment]
> So it shouldn't create any merge conflicts if we merge #1501 first and then this.

#1501 has been merged, the only conflict was

`"sinon": "2.0.0-pre,  ->  "sinon": "2.0.0-pre.5",`

I fixed that. This PR should be good to go after CI builds pass and one more maintainer approves.

**Pull request merged**
