### PR TITLE
Next version update

### PR DESCRIPTION
**Pull request by gretzky**
I just ran through the dev branch and had no issues. I don't see any reason why we shouldn't kick this merge off. 

I suggest we bump the version to be 3.6.0, since I believe there's enough change dependency-wise and configuration wise that it merits more than just a patch. 

There's definitely a lot to explore with this bp, but for now I think we should get this rolling. Any help merging is appreciated. I'd say that anything with all checks passed should be pulled in.

### CODE REVIEW

**Comment by julienben** [comment]
@gretzky Hey Sara, Just a quick reply to LYK I'm away on holiday until next weekend. I won't be able to review until the week of the 21st. In any case, wouldn't it be better to first resolve the long list of conflicts before reviewing?

**Comment by gretzky** [comment]
@julienben I can get started on conflicts -- I'll see how much it takes while you're gone and if its realistic to continue when you get back I'll let you know

**Comment by blling** [comment]
Maybe we should remove `dev` branch and use `master` as the develop branch?

**Comment by gretzky** [comment]
@blling I'm honestly kind of in favor for this.

I started going through the dev branch and it def seems out of control. @julienben (welcome back from holiday), I'm gonna fork this bp and make some fundamental updates (versioning, and any code changes that come along)-- and then I'll tag you guys in a PR to see if we can get it going.

Closing in favor of smaller updates, which I knew all along was the better way to go... 😅

**Comment by julienben** [comment]
Hey @gretzky, I didn't understand what you meant exactly. Are you working on a version 3.6 in a fork? Is this work that will be merged back into this repo or is it for a different one?

@blling In your suggestion, would we still merge develop into master? Do we merge conflicts or "force merge"?

**Comment by gretzky** [comment]
@julienben sorry I definitely said 2 different things there. I'm working on a fork that we can merge back in that addresses the following:

- Upgrade React to v16
- Upgrade Redux to v4
- Upgrade Webpack to v4
- Updating all dependencies
- Updating to Enzyme v3
- Reworking the webpack config (to work w/ version upgrade and to enhance it)
- Reworking Enzyme tests (to work w/ version upgrade)
- Reworking any other minor code pieces that are affected by dependency updates
- If I get around to it, making use of new React v16 feature (fragment, etc.) but this is low priority

I'm going to be cherry-picking from some PRs that got merged into `dev` that cover some of the above as well. I'd say we should call it v3.6 because there are so many updates to major dependencies.

**Comment by blling** [comment]
@julienben @gretzky i think we should merge `master` into `dev` and resolve the conflicts, then merge `dev` into `master`, and then delete `dev`. Maybe this is an easy and safe way?

**Comment by julienben** [comment]
It sounds like @gretzky is working on a branch she forked from master, right? If that's the case, we don't need to merge `dev` anyway. We can just decide whether or not we want to delete it after @gretzky's PR.

**Comment by blling** [comment]
Sounds good.

**Pull request closed without merging**
