### PR TITLE
Migrating to react-testing-library

### PR DESCRIPTION
**Pull request by julienben**
All of @Mensae's work from #2589 and #2473.

- [x] You have followed our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md)
- [x] Double-check your branch is based on `dev` and targets `dev` 
- [x] Pull request has tests (we are going for 100% coverage!)
- [x] Code is well-commented, linted and follows project conventions
- [x] Documentation is updated (if necessary)
- [x] Internal code generators and templates are updated (if necessary)
- [x] Description explains the issue/use-case resolved and auto-closes related issues

### CODE REVIEW

**Comment by julienben** [comment]
@Mensae Do you know what's happening [here](https://ci.appveyor.com/project/justingreenberg/react-boilerplate/builds/22848893/job/9ngyd9srlefgt61i) by any chance?

**Comment by julienben** [comment]
image
Weirdly this only happens in LTS...

**Comment by Mensae** [comment]
🤔 intersting. I'll try to have a look at it today.

**Comment by julienben** [comment]
The good news: AppVeyor passes! Your fix is 👌!
The bad news: Travis has started failing us on Node 11.11 (not LTS) pretty much out of nowhere. It happens for all branches but we can't merge anything into dev until it's fixed. 😓

**Comment by julienben** [comment]
It's a bug between Jest and Node 11.11 (which is used by Travis to run our tests). I upgraded jest-cli and it should be fixed.

**Comment by Mensae** [comment]
Yes! 🙂

Yes, I saw Travis failing but was scared to look right before bedtime. Hopefully the upgrade will fix it, fingers crossed

**Comment by julienben** [comment]
It's fixed. We just need someone else from the team to review before we can merge!

**Comment by gretzky** [comment]
Excellent work @Mensae thank you, I've been wanting to move to react-testing-library at work but needed some frame of reference for it 🙌  This is a great addition, happy to merge. (and of course shoutout my buddy @julienben)

**Pull request merged**
