### PR TITLE
chore(docs): Update link to redux-saga repository

### PR DESCRIPTION
**Pull request by andersravn**
## React Boilerplate

Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.

**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.

Before opening a pull request, please ensure:

- [ ] You have followed our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md)
- [ ] double-check your branch is based on `dev` and targets `dev` 
- [ ] Pull request has tests (we are going for 100% coverage!)
- [ ] Code is well-commented, linted and follows project conventions
- [ ] Documentation is updated (if necessary)
- [ ] Internal code generators and templates are updated (if necessary)
- [ ] Description explains the issue/use-case resolved and auto-closes related issues

Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)

**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [MIT License](https://github.com/react-boilerplate/react-boilerplate/blob/master/LICENSE.md).

### CODE REVIEW

**Comment by andersravn** [comment]
Rather I meant: The link to Redux Saga wasn't working.

**Comment by justingreenberg** [comment]
@andersravn thank you for catching this! :)  new PRs need to be made against `dev` branch, would you mind creating a new PR? in the meantime i'm going to close this one

**Comment by andersravn** [comment]
@justingreenberg On the dev branch, it actually links to https://redux-saga.github.io/redux-saga/, which hosts to the react-router repo. Is this also wrong? Maybe it would be easier if you just change the url. :D

**Comment by justingreenberg** [comment]
@andersravn no worries, i think current link to docs on `dev` is good... thanks again :)

**Comment by andersravn** [comment]
No problem! Have a nice day. :)

**Comment by KarandikarMihir** [comment]
@andersravn It was already fixed :) Thanks for the efforts though.

**Pull request closed without merging**
